import { useMemo, useState } from 'react';
import { Shuffle, Target } from 'lucide-react';
import { columnMaxima,maximin,minimax,payoffMatrix,rowMinima,saddlePoints,solveZeroSum2x2,strictlyDominatedColumns,strictlyDominatedRows } from '@amat19/domain-games';
import { Button } from '../../ui/Button';import { Feedback } from '../../ui/Feedback';import { Badge } from '../../ui/Badge';import { recordAttempt,recordSkillEvidence } from '../../../lib/local-progress';
const PRESETS={mixed:[['4','0'],['1','3']],saddle:[['3','1'],['4','2']],dominance:[['5','4'],['2','1']]} as const;
export default function GameTheoryLab(){
 const[values,setValues]=useState<string[][]>(PRESETS.mixed.map(row=>[...row])),[prediction,setPrediction]=useState<'pure'|'mixed'>(),[checked,setChecked]=useState(false);
 const out=useMemo(()=>{try{const A=payoffMatrix(values);return{A,rows:rowMinima(A),cols:columnMaxima(A),low:maximin(A),high:minimax(A),saddles:saddlePoints(A),rowDom:strictlyDominatedRows(A),colDom:strictlyDominatedColumns(A),solution:solveZeroSum2x2(A),error:undefined}}catch(error){return{error:error instanceof Error?error.message:'Game matrix could not be analyzed.'}}},[values]);
 const set=(r:number,c:number,v:string)=>setValues(current=>current.map((row,i)=>i===r?row.map((x,j)=>j===c?v:x):row));
 async function check(){if(!prediction||!out.solution)return;const expected=out.solution.kind==='pure'?'pure':'mixed';const ok=prediction===expected;setChecked(true);await Promise.all([recordAttempt({prefix:'game',exerciseId:'applications.game.solution-type',module:'applications',finalState:ok?'correct':'incomplete',payload:{values,prediction,kind:out.solution.kind},skillIds:['games.saddle']}),recordSkillEvidence('games.saddle',ok?1:0,{independent:ok})]).catch(()=>undefined)}
 function preset(name:keyof typeof PRESETS){setValues(PRESETS[name].map(row=>[...row]));setPrediction(undefined);setChecked(false)}
 return <section className="game-lab" data-testid="game-theory-lab"><div className="game-lab__matrix"><p className="section-label">Two-person zero-sum game</p><h2>Security first. Mixing only when pure strategies cannot meet.</h2><p>Entries are the row player's payoff. The row player maximizes; the column player minimizes.</p><div className="preset-row"><button className="text-chip" onClick={()=>preset('mixed')}>Mixed example</button><button className="text-chip" onClick={()=>preset('saddle')}>Saddle example</button><button className="text-chip" onClick={()=>preset('dominance')}>Dominance example</button></div><table className="payoff-table"><thead><tr><th></th><th>Column 1</th><th>Column 2</th><th>Row minimum</th></tr></thead><tbody>{values.map((row,r)=><tr key={r} data-dominated={out.rowDom?.some(item=>item.dominated===r)}><th>Row {r+1}</th>{row.map((v,c)=><td key={c} data-dominated={out.colDom?.some(item=>item.dominated===c)}><input aria-label={`Payoff row ${r+1} column ${c+1}`} value={v} onChange={e=>set(r,c,e.target.value)}/></td>)}<td>{out.rows?.[r]?.toString()??'—'}</td></tr>)}<tr><th>Column maximum</th>{out.cols?.map((v,c)=><td key={c}>{v.toString()}</td>)}<td></td></tr></tbody></table><fieldset className="prediction-fieldset"><legend>Predict the solution type</legend><label><input type="radio" checked={prediction==='pure'} onChange={()=>{setPrediction('pure');setChecked(false)}}/> Pure saddle-point strategy</label><label><input type="radio" checked={prediction==='mixed'} onChange={()=>{setPrediction('mixed');setChecked(false)}}/> No saddle point; mixing is needed</label><Button disabled={!prediction||!out.solution} onClick={()=>void check()}>Check prediction</Button>{checked&&out.solution&&<Feedback tone={(prediction==='pure')===(out.solution.kind==='pure')?'success':'error'}>{out.solution.kind==='pure'?'Maximin equals minimax, so a saddle point exists.':'The security levels do not meet at one pure payoff; inspect the mixed-strategy analysis.'}</Feedback>}</fieldset></div>
 <div className="game-lab__analysis">{out.error?<Feedback tone="error">{out.error}</Feedback>:<><div className="security-grid"><div className="formula-callout"><span>Row player's maximin</span><strong>{out.low?.toString()}</strong></div><div className="formula-callout"><span>Column player's minimax</span><strong>{out.high?.toString()}</strong></div></div>{out.saddles&&out.saddles.length>0?<div className="formula-callout"><span>Pure saddle point</span><strong>Row {out.saddles[0]!.row+1}, Column {out.saddles[0]!.col+1}; value = {out.saddles[0]!.value.toString()}</strong></div>:<><MixedSolution solution={out.solution}/><PayoffMixPlot values={values.map(row=>row.map(Number))} solution={out.solution}/></>}<div className="dominance-list"><div className="math-panel__head"><div><p className="section-label">Strict dominance scan</p><h3>Remove strategies that are always worse.</h3></div><Badge>{(out.rowDom?.length??0)+(out.colDom?.length??0)} dominated</Badge></div>{out.rowDom?.length?<p>Row {out.rowDom[0]!.dominated+1} is strictly dominated by Row {out.rowDom[0]!.by+1}.</p>:<p>No strictly dominated row detected.</p>}{out.colDom?.length?<p>Column {out.colDom[0]!.dominated+1} is strictly dominated by Column {out.colDom[0]!.by+1} for the minimizing player.</p>:<p>No strictly dominated column detected.</p>}</div></>}</div><aside className="game-lab__explain"><p className="section-label">Interpretation</p><p><strong>Maximin:</strong> each row's worst payoff, then choose the largest.</p><p><strong>Minimax:</strong> each column's worst exposure for the minimizer, then choose the smallest.</p><p>A pure saddle point exists only when these security values are equal at the same cell.</p><p className="experimental-note">The 2×2 mixed-strategy surface stays intentionally zero-sum and bounded; it does not pretend to be a general Nash-equilibrium solver.</p></aside></section>
}
function MixedSolution({solution}:{solution:any}){if(!solution)return null;if(solution.kind==='mixed')return <div className="mixed-grid"><div className="formula-callout"><span>Row mix</span><strong>p(Row 1) = {solution.pRow1.toString()}</strong><small>p(Row 2) = {solution.pRow2.toString()}</small></div><div className="formula-callout"><span>Column mix</span><strong>q(Column 1) = {solution.qCol1.toString()}</strong><small>q(Column 2) = {solution.qCol2.toString()}</small></div><div className="formula-callout"><span>Game value</span><strong>{solution.value.toString()}</strong></div></div>;if(solution.kind==='boundary'||solution.kind==='degenerate')return <Feedback tone="warning">{solution.reason}</Feedback>;return null}
function PayoffMixPlot({values,solution}:{values:number[][];solution:any}){if(!solution||solution.kind!=='mixed'||values.some(row=>row.some(value=>!Number.isFinite(value))))return null;const [[a,b],[c,d]]=values as [[number,number],[number,number]];const f1=(q:number)=>b+q*(a-b),f2=(q:number)=>d+q*(c-d);const ys=[f1(0),f1(1),f2(0),f2(1),solution.value.toNumber()];const min=Math.min(...ys)-1,max=Math.max(...ys)+1,sy=(v:number)=>235-(v-min)/(max-min)*180,sx=(q:number)=>55+500*q;const q=solution.qCol1.toNumber(),v=solution.value.toNumber();return <figure className="game-payoff-plot"><svg viewBox="0 0 610 270" role="img" aria-label="Expected row payoffs as the column player mixes"><line x1="55" y1="235" x2="555" y2="235" stroke="currentColor"/><line x1="55" y1="235" x2="55" y2="35" stroke="currentColor"/><path className="payoff-line payoff-line--a" d={`M ${sx(0)} ${sy(f1(0))} L ${sx(1)} ${sy(f1(1))}`}/><path className="payoff-line payoff-line--b" d={`M ${sx(0)} ${sy(f2(0))} L ${sx(1)} ${sy(f2(1))}`}/><circle className="mix-point" cx={sx(q)} cy={sy(v)} r="7"/><text x={sx(q)+10} y={sy(v)-8}>q={q.toFixed(3)}, value={v.toFixed(3)}</text><text x="55" y="258">q=0</text><text x="525" y="258">q=1</text></svg><figcaption>The minimizing player chooses q where the two row payoffs meet, making the maximizing player indifferent between rows.</figcaption></figure>}
