import { useMemo, useState } from 'react';
import { columnMaxima, maximin, minimax, payoffMatrix, rowMinima, saddlePoints, solveZeroSum2x2, strictlyDominatedColumns, strictlyDominatedRows } from '@amat19/domain-games';
import { Button } from '../../ui/Button';
import { Feedback } from '../../ui/Feedback';
import { recordAttempt, recordSkillEvidence } from '../../../lib/local-progress';
const PRESETS = { mixed: [['4', '0'], ['1', '3']], saddle: [['3', '1'], ['4', '2']], dominance: [['5', '4'], ['2', '1']] } as const;

export default function GameTheoryLab() {
  const [values, setValues] = useState<string[][]>(PRESETS.mixed.map((row) => [...row])), [prediction, setPrediction] = useState<'pure' | 'mixed'>(), [checked, setChecked] = useState(false);
  const out = useMemo(() => { try { const A = payoffMatrix(values); return { A, rows: rowMinima(A), cols: columnMaxima(A), low: maximin(A), high: minimax(A), saddles: saddlePoints(A), rowDom: strictlyDominatedRows(A), colDom: strictlyDominatedColumns(A), solution: solveZeroSum2x2(A), error: undefined }; } catch (error) { return { error: error instanceof Error ? error.message : 'Game matrix could not be analyzed.' }; } }, [values]);
  const set = (row: number, col: number, value: string) => setValues((current) => current.map((items, i) => i === row ? items.map((item, j) => j === col ? value : item) : items));
  async function check() { if (!prediction || !out.solution) return; const expected = out.solution.kind === 'pure' ? 'pure' : 'mixed'; const ok = prediction === expected; setChecked(true); await Promise.all([recordAttempt({ prefix: 'game', exerciseId: 'applications.game.solution-type', module: 'applications', finalState: ok ? 'correct' : 'incomplete', payload: { values, prediction, kind: out.solution.kind }, skillIds: ['games.saddle'] }), recordSkillEvidence('games.saddle', ok ? 1 : 0, { independent: ok })]).catch(() => undefined); }
  function preset(name: keyof typeof PRESETS) { setValues(PRESETS[name].map((row) => [...row])); setPrediction(undefined); setChecked(false); }

  return <section className="game-instrument" data-testid="game-theory-lab">
    <div className="game-instrument__toolbar"><div className="preset-row"><button type="button" className="text-chip" onClick={() => preset('mixed')}>Mixed example</button><button type="button" className="text-chip" onClick={() => preset('saddle')}>Saddle example</button><button type="button" className="text-chip" onClick={() => preset('dominance')}>Dominance example</button></div><span>Row player maximizes · column player minimizes</span></div>

    <div className="game-instrument__canvas"><div className="game-instrument__head"><div><h2>Security values live on the edges of the matrix.</h2><p className="section-label">Payoff matrix</p></div>{out.low && out.high && <div className="security-equation"><span>maximin</span><strong>{out.low.toString()}</strong><span>minimax</span><strong>{out.high.toString()}</strong></div>}</div>
      {out.error ? <Feedback tone="error">{out.error}</Feedback> : <table className="payoff-table payoff-table--instrument"><thead><tr><th scope="col">Row \ Column</th><th scope="col" data-dominated={out.colDom?.some((item) => item.dominated === 0)}>C1</th><th scope="col" data-dominated={out.colDom?.some((item) => item.dominated === 1)}>C2</th><th scope="col" className="payoff-security-edge">row min</th></tr></thead><tbody>{values.map((row, r) => <tr key={r} data-dominated={out.rowDom?.some((item) => item.dominated === r)}><th scope="row">R{r + 1}</th>{row.map((value, c) => { const saddle = out.saddles?.some((item) => item.row === r && item.col === c); return <td key={c} data-saddle={saddle} data-dominated={out.colDom?.some((item) => item.dominated === c)}><input aria-label={`Payoff row ${r + 1} column ${c + 1}`} value={value} onChange={(event) => set(r, c, event.target.value)} />{saddle && <span className="saddle-mark" aria-label="saddle point">×</span>}</td>; })}<td className="payoff-security-edge"><strong>{out.rows?.[r]?.toString() ?? '—'}</strong></td></tr>)}<tr className="payoff-security-row"><th scope="row">column max</th>{out.cols?.map((value, col) => <td key={col}><strong>{value.toString()}</strong></td>)}<td aria-hidden="true"></td></tr></tbody></table>}
      {!out.error && out.saddles && out.saddles.length === 0 && <PayoffMixPlot values={values.map((row) => row.map(Number))} solution={out.solution} />}
    </div>

    <aside className="game-instrument__inspector" aria-label="Game solution inspector"><p className="section-label">Solution</p>{!out.error && <>{out.saddles && out.saddles.length > 0 ? <div className="game-solution-line"><span>Pure saddle</span><strong>R{out.saddles[0]!.row + 1}, C{out.saddles[0]!.col + 1}</strong><small>value = {out.saddles[0]!.value.toString()}</small></div> : <MixedSolution solution={out.solution} />}<div className="dominance-ledger"><span>Dominance</span>{out.rowDom?.length ? <p>R{out.rowDom[0]!.dominated + 1} is strictly dominated by R{out.rowDom[0]!.by + 1}.</p> : <p>No dominated row.</p>}{out.colDom?.length ? <p>C{out.colDom[0]!.dominated + 1} is strictly dominated by C{out.colDom[0]!.by + 1}.</p> : <p>No dominated column.</p>}</div></>}
      <fieldset className="prediction-fieldset"><legend>Predict solution type</legend><label><input type="radio" name="game-solution-type" checked={prediction === 'pure'} onChange={() => { setPrediction('pure'); setChecked(false); }} /> Pure saddle point</label><label><input type="radio" name="game-solution-type" checked={prediction === 'mixed'} onChange={() => { setPrediction('mixed'); setChecked(false); }} /> Mixing required</label><Button disabled={!prediction || !out.solution} onClick={() => void check()}>Check prediction</Button>{checked && out.solution && <Feedback tone={(prediction === 'pure') === (out.solution.kind === 'pure') ? 'success' : 'error'}>{out.solution.kind === 'pure' ? 'Maximin and minimax meet at one cell.' : 'The security levels do not meet at a pure payoff.'}</Feedback>}</fieldset>
    </aside>
  </section>;
}
function MixedSolution({ solution }: { solution: any }) { if (!solution) return null; if (solution.kind === 'mixed') return <div className="mixed-solution-ledger"><div><span>Row mix</span><strong>p(R1) = {solution.pRow1.toString()}</strong><small>p(R2) = {solution.pRow2.toString()}</small></div><div><span>Column mix</span><strong>q(C1) = {solution.qCol1.toString()}</strong><small>q(C2) = {solution.qCol2.toString()}</small></div><div><span>Game value</span><strong>{solution.value.toString()}</strong></div></div>; if (solution.kind === 'boundary' || solution.kind === 'degenerate') return <Feedback tone="warning">{solution.reason}</Feedback>; return null; }
function PayoffMixPlot({ values, solution }: { values: number[][]; solution: any }) { if (!solution || solution.kind !== 'mixed' || values.some((row) => row.some((value) => !Number.isFinite(value)))) return null; const [[a, b], [c, d]] = values as [[number, number], [number, number]]; const f1 = (q: number) => b + q * (a - b), f2 = (q: number) => d + q * (c - d); const ys = [f1(0), f1(1), f2(0), f2(1), solution.value.toNumber()]; const min = Math.min(...ys) - 1, max = Math.max(...ys) + 1, sy = (v: number) => 235 - (v - min) / (max - min) * 180, sx = (q: number) => 55 + 500 * q; const q = solution.qCol1.toNumber(), v = solution.value.toNumber(); return <figure className="game-payoff-plot"><svg viewBox="0 0 610 270" role="img" aria-label="Expected row payoffs as the column player mixes"><line x1="55" y1="235" x2="555" y2="235" /><line x1="55" y1="235" x2="55" y2="35" /><path className="payoff-line payoff-line--a" d={`M ${sx(0)} ${sy(f1(0))} L ${sx(1)} ${sy(f1(1))}`} /><path className="payoff-line payoff-line--b" d={`M ${sx(0)} ${sy(f2(0))} L ${sx(1)} ${sy(f2(1))}`} /><circle className="mix-point" cx={sx(q)} cy={sy(v)} r="7" /><line className="mix-guide" x1={sx(q)} y1={sy(v)} x2={sx(q)} y2="235" /><text x={sx(q) + 10} y={sy(v) - 8}>q={q.toFixed(3)}, value={v.toFixed(3)}</text><text x="55" y="258">q=0</text><text x="525" y="258">q=1</text></svg><figcaption>The intersection is the mix that makes the maximizing player indifferent between rows.</figcaption></figure>; }
