import { useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, RotateCcw } from 'lucide-react';
import { distribution,distributionAfter,matrixPower,matrixToStrings,stationaryTwoState,transitionMatrix } from '@amat19/domain-linear';
import { Button } from '../../ui/Button';import { Feedback } from '../../ui/Feedback';import { Badge } from '../../ui/Badge';
export default function MarkovLab(){
 const[p00,setP00]=useState('3/4'),[p01,setP01]=useState('1/4'),[p10,setP10]=useState('1/2'),[p11,setP11]=useState('1/2'),[d0,setD0]=useState('1'),[d1,setD1]=useState('0'),[steps,setSteps]=useState(3),[name0,setName0]=useState('State 1'),[name1,setName1]=useState('State 2');
 const out=useMemo(()=>{try{const P=transitionMatrix([[p00,p01],[p10,p11]]),d=distribution([d0,d1]),after=distributionAfter(d,P,steps),Pk=matrixPower(P,steps);let stationary;try{stationary=stationaryTwoState(P)}catch{}const trajectory=Array.from({length:steps+1},(_,k)=>distributionAfter(d,P,k));return{P,d,after,Pk,stationary,trajectory,error:undefined}}catch(error){return{error:error instanceof Error?error.message:'Markov model is invalid.'}}},[p00,p01,p10,p11,d0,d1,steps]);
 return <section className="markov-lab" data-testid="markov-lab"><div className="markov-lab__controls"><h2>Follow probability mass one transition at a time.</h2><p className="section-context">Supplemental · Markov chain</p><div className="two-column-fields"><label className="form-field"><span className="form-field__label">State 1 name</span><input className="text-input" value={name0} onChange={e=>setName0(e.target.value)}/></label><label className="form-field"><span className="form-field__label">State 2 name</span><input className="text-input" value={name1} onChange={e=>setName1(e.target.value)}/></label></div><div className="markov-matrix-editor"><label>{name0} → {name0}<input value={p00} onChange={e=>setP00(e.target.value)}/></label><label>{name0} → {name1}<input value={p01} onChange={e=>setP01(e.target.value)}/></label><label>{name1} → {name0}<input value={p10} onChange={e=>setP10(e.target.value)}/></label><label>{name1} → {name1}<input value={p11} onChange={e=>setP11(e.target.value)}/></label></div><div className="number-pair"><label className="form-field"><span className="form-field__label">Initial P({name0})</span><input className="text-input" value={d0} onChange={e=>setD0(e.target.value)}/></label><label className="form-field"><span className="form-field__label">Initial P({name1})</span><input className="text-input" value={d1} onChange={e=>setD1(e.target.value)}/></label></div><div className="markov-stepper"><Button variant="ghost" aria-label="Previous Markov step" disabled={steps<=0} onClick={()=>setSteps(k=>Math.max(0,k-1))}><ChevronLeft size={15}/></Button><input type="range" min="0" max="20" value={steps} onChange={e=>setSteps(Number(e.target.value))} aria-label="Markov step k"/><Button variant="ghost" aria-label="Next Markov step" disabled={steps>=20} onClick={()=>setSteps(k=>Math.min(20,k+1))}><ChevronRight size={15}/></Button><Badge>k = {steps}</Badge><Button variant="ghost" onClick={()=>setSteps(0)}><RotateCcw size={14}/> reset k</Button></div>{out.error&&<Feedback tone="error">{out.error}</Feedback>}</div>
 <div className="markov-lab__visual">{!out.error&&out.P&&<><MarkovGraph values={[[p00,p01],[p10,p11]]} names={[name0,name1]}/><div className="formula-callout"><span>Distribution after {steps} step{steps===1?'':'s'}</span><strong>[{out.after!.map(value=>value.toString()).join(', ')}]</strong></div>{out.stationary&&<div className="formula-callout"><span>Stationary distribution</span><strong>[{out.stationary.map(value=>value.toString()).join(', ')}]</strong><small>Starting here leaves the distribution unchanged after one transition.</small></div>}<div className="markov-trajectory"><p className="section-label">State-vector trajectory</p>{out.trajectory?.map((row,k)=><div key={k} data-current={k===steps}><strong>k={k}</strong><span>{name0}: {row[0]!.toString()}</span><span>{name1}: {row[1]!.toString()}</span></div>)}</div></>}</div><aside className="markov-lab__matrix"><p className="section-label">k-step transition matrix P^{steps}</p>{out.Pk&&<table className="matrix-table"><tbody>{matrixToStrings(out.Pk).map((row,i)=><tr key={i}>{row.map((value,j)=><td key={j}>{value}</td>)}</tr>)}</tbody></table>}<p className="experimental-note">The graph, state vector, and k-step matrix are synchronized views of the same exact transition model.</p></aside></section>
}
function MarkovGraph({values,names}:{values:string[][];names:[string,string]}){return <figure className="markov-graph"><svg viewBox="0 0 600 260" role="img" aria-label="Two state Markov transition graph"><circle cx="170" cy="130" r="55"/><circle cx="430" cy="130" r="55"/><text x="170" y="135" textAnchor="middle">{names[0]}</text><text x="430" y="135" textAnchor="middle">{names[1]}</text><path d="M225 115 C300 65 350 65 375 115"/><path d="M375 145 C320 200 270 200 225 145"/><text x="300" y="75" textAnchor="middle">{values[0]![1]}</text><text x="300" y="210" textAnchor="middle">{values[1]![0]}</text><path d="M145 75 C70 10 70 110 120 110"/><text x="70" y="55">{values[0]![0]}</text><path d="M455 75 C530 10 530 110 480 110"/><text x="510" y="55">{values[1]![1]}</text></svg></figure>}
