import { useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, RotateCcw } from 'lucide-react';
import { distribution, distributionAfter, matrixPower, matrixToStrings, stationaryTwoState, transitionMatrix } from '@amat19/domain-linear';
import { Button } from '../../ui/Button';
import { Feedback } from '../../ui/Feedback';

export default function MarkovLab() {
  const [p00, setP00] = useState('3/4'), [p01, setP01] = useState('1/4'), [p10, setP10] = useState('1/2'), [p11, setP11] = useState('1/2');
  const [d0, setD0] = useState('1'), [d1, setD1] = useState('0'), [steps, setSteps] = useState(3), [name0, setName0] = useState('State 1'), [name1, setName1] = useState('State 2');
  const out = useMemo(() => { try { const P = transitionMatrix([[p00, p01], [p10, p11]]), d = distribution([d0, d1]), after = distributionAfter(d, P, steps), Pk = matrixPower(P, steps); let stationary; try { stationary = stationaryTwoState(P); } catch {} const trajectory = Array.from({ length: steps + 1 }, (_, k) => distributionAfter(d, P, k)); return { P, d, after, Pk, stationary, trajectory, error: undefined }; } catch (error) { return { error: error instanceof Error ? error.message : 'Markov model is invalid.' }; } }, [p00, p01, p10, p11, d0, d1, steps]);

  return <section className="markov-instrument" data-testid="markov-lab">
    <div className="markov-instrument__toolbar"><div className="markov-stepper"><Button variant="ghost" aria-label="Previous Markov step" disabled={steps <= 0} onClick={() => setSteps((k) => Math.max(0, k - 1))}><ChevronLeft size={15} /></Button><input type="range" min="0" max="20" value={steps} onChange={(event) => setSteps(Number(event.target.value))} aria-label="Markov step k" /><strong>k = {steps}</strong><Button variant="ghost" aria-label="Next Markov step" disabled={steps >= 20} onClick={() => setSteps((k) => Math.min(20, k + 1))}><ChevronRight size={15} /></Button><Button variant="ghost" onClick={() => setSteps(0)}><RotateCcw size={14} /> reset</Button></div></div>

    <aside className="markov-instrument__controls" aria-label="Transition model controls"><div><h2>Follow probability mass one step at a time.</h2><p className="section-label">Transition model</p><p className="instrument-note">The graph, matrix, state vector, and trajectory are synchronized views of one exact transition model.</p></div><div className="two-column-fields"><label className="form-field"><span className="form-field__label">State 1</span><input className="text-input" value={name0} onChange={(event) => setName0(event.target.value)} /></label><label className="form-field"><span className="form-field__label">State 2</span><input className="text-input" value={name1} onChange={(event) => setName1(event.target.value)} /></label></div><div className="markov-matrix-editor"><label>{name0} → {name0}<input value={p00} onChange={(event) => setP00(event.target.value)} /></label><label>{name0} → {name1}<input value={p01} onChange={(event) => setP01(event.target.value)} /></label><label>{name1} → {name0}<input value={p10} onChange={(event) => setP10(event.target.value)} /></label><label>{name1} → {name1}<input value={p11} onChange={(event) => setP11(event.target.value)} /></label></div><div className="number-pair"><label className="form-field"><span className="form-field__label">Initial P({name0})</span><input className="text-input" value={d0} onChange={(event) => setD0(event.target.value)} /></label><label className="form-field"><span className="form-field__label">Initial P({name1})</span><input className="text-input" value={d1} onChange={(event) => setD1(event.target.value)} /></label></div>{out.error && <Feedback tone="error">{out.error}</Feedback>}</aside>

    <div className="markov-instrument__canvas">{!out.error && out.P && <><div className="markov-synchronized"><MarkovGraph values={[[p00, p01], [p10, p11]]} names={[name0, name1]} /><div className="markov-matrix-pair"><div><span>P</span><MatrixTable rows={matrixToStrings(out.P)} /></div><div className="markov-power-sign">→<small>k={steps}</small></div><div><span>P^{steps}</span><MatrixTable rows={matrixToStrings(out.Pk!)} /></div></div></div><div className="markov-state-strip"><span>d₀</span><strong>[{out.d!.map((value) => value.toString()).join(', ')}]</strong><span>→ d{steps}</span><strong>[{out.after!.map((value) => value.toString()).join(', ')}]</strong></div>{out.stationary && <div className="markov-stationary"><span>stationary π</span><strong>[{out.stationary.map((value) => value.toString()).join(', ')}]</strong><small>πP = π</small></div>}</>}</div>

    <aside className="markov-instrument__inspector" aria-label="State-vector trajectory"><p className="section-label">Trajectory</p><div className="markov-trajectory">{out.trajectory?.map((row, k) => <div key={k} data-current={k === steps}><strong>k={k}</strong><span>{name0}: {row[0]!.toString()}</span><span>{name1}: {row[1]!.toString()}</span></div>)}</div></aside>
  </section>;
}
function MatrixTable({ rows }: { rows: string[][] }) { return <div className="markov-matrix-bracket"><table className="matrix-table"><tbody>{rows.map((row, i) => <tr key={i}>{row.map((value, j) => <td key={j}>{value}</td>)}</tr>)}</tbody></table></div>; }
function MarkovGraph({ values, names }: { values: string[][]; names: [string, string] }) { return <figure className="markov-graph"><svg viewBox="0 0 600 280" role="img" aria-label="Two-state Markov transition graph"><defs><marker id="markovArrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" /></marker></defs><circle cx="170" cy="140" r="58" /><circle cx="430" cy="140" r="58" /><text x="170" y="145" textAnchor="middle">{names[0]}</text><text x="430" y="145" textAnchor="middle">{names[1]}</text><path className="markov-transition" markerEnd="url(#markovArrow)" d="M225 120 C300 68 350 68 375 120" /><path className="markov-transition" markerEnd="url(#markovArrow)" d="M375 160 C320 212 270 212 225 160" /><text x="300" y="73" textAnchor="middle">{values[0]![1]}</text><text x="300" y="225" textAnchor="middle">{values[1]![0]}</text><path className="markov-transition" markerEnd="url(#markovArrow)" d="M145 82 C70 12 70 118 118 118" /><text x="76" y="56">{values[0]![0]}</text><path className="markov-transition" markerEnd="url(#markovArrow)" d="M455 82 C530 12 530 118 482 118" /><text x="508" y="56">{values[1]![1]}</text></svg><figcaption>Each outgoing row of P distributes the current state's probability mass.</figcaption></figure>; }
