export const FINANCE_SCALE_DIGITS=30;
export const MAX_FINANCE_TEXT_LENGTH=512;
export const MAX_FINANCE_EXPONENT_MAGNITUDE=1_000;
export const MAX_FINANCE_INTEGER_DIGITS=300;
const SCALE_DIGITS=FINANCE_SCALE_DIGITS;
const SCALE=10n**BigInt(SCALE_DIGITS);
const MAX_FINANCE_RAW_DIGITS=SCALE_DIGITS+MAX_FINANCE_INTEGER_DIGITS;
function abs(v:bigint){return v<0n?-v:v}
function gcd(a:bigint,b:bigint):bigint{a=abs(a);b=abs(b);while(b!==0n){[a,b]=[b,a%b]}return a||1n}
function assertRawBudget(raw:bigint):bigint{const digits=abs(raw).toString().length;if(raw!==0n&&digits>MAX_FINANCE_RAW_DIGITS)throw new RangeError(`Finance value magnitude cannot exceed ${MAX_FINANCE_INTEGER_DIGITS} integer digits at ${FINANCE_SCALE_DIGITS}-digit precision.`);return raw}
function parsePlain(value:string):bigint{
 const text=value.trim();if(!text)throw new TypeError('Decimal value is empty.');if(text.length>MAX_FINANCE_TEXT_LENGTH)throw new RangeError(`Finance decimal input cannot exceed ${MAX_FINANCE_TEXT_LENGTH} characters.`);
 const match=text.match(/^([+-]?)(?:(\d+)(?:\.(\d*))?|\.(\d+))(?:[eE]([+-]?\d+))?$/);if(!match)throw new TypeError('Invalid decimal value.');
 const sign=match[1]==='-'?-1n:1n,whole=match[2]??'0',fraction=match[3]??match[4]??'';const exponentText=match[5];
 const exponent=exponentText===undefined?0:Number(exponentText);if(!Number.isSafeInteger(exponent))throw new TypeError('Invalid decimal exponent.');if(Math.abs(exponent)>MAX_FINANCE_EXPONENT_MAGNITUDE)throw new RangeError(`Finance decimal exponent magnitude cannot exceed ${MAX_FINANCE_EXPONENT_MAGNITUDE}.`);
 let digits=`${whole}${fraction}`.replace(/^0+(?=\d)/,'');let decimalPlaces=fraction.length-exponent;
 if(decimalPlaces<0){digits+='0'.repeat(-decimalPlaces);decimalPlaces=0;}
 if(decimalPlaces>SCALE_DIGITS){const remove=decimalPlaces-SCALE_DIGITS,cut=Math.max(0,digits.length-remove),keep=digits.slice(0,cut),discarded=digits.slice(cut);let raw=BigInt(keep||'0');if(discarded[0]&&discarded[0]>='5')raw+=1n;return assertRawBudget(sign*raw);}
 const raw=BigInt(digits||'0')*10n**BigInt(SCALE_DIGITS-decimalPlaces);return assertRawBudget(sign*raw);
}
function divRound(numerator:bigint,denominator:bigint):bigint{if(denominator===0n)throw new RangeError('Division by zero.');const sign=(numerator<0n)!==(denominator<0n)?-1n:1n;const n=abs(numerator),d=abs(denominator);const q=n/d,r=n%d;return sign*(q+(r*2n>=d?1n:0n));}
export class FinanceDecimal{
 readonly raw:bigint;
 private constructor(raw:bigint){this.raw=assertRawBudget(raw)}
 static from(value:FinanceDecimal|number|string|bigint):FinanceDecimal{if(value instanceof FinanceDecimal)return value;if(typeof value==='bigint')return new FinanceDecimal(value*SCALE);if(typeof value==='number'){if(!Number.isFinite(value))throw new RangeError('Finance values must be finite.');if(Math.abs(value)>Number.MAX_SAFE_INTEGER)throw new RangeError('Finance numbers outside the safe JavaScript numeric range must be supplied as decimal text or bigint.');return new FinanceDecimal(parsePlain(String(value)));}return new FinanceDecimal(parsePlain(value));}
 static zero(){return new FinanceDecimal(0n)} static one(){return new FinanceDecimal(SCALE)}
 add(other:FinanceDecimal|number|string|bigint){return new FinanceDecimal(this.raw+FinanceDecimal.from(other).raw)}
 subtract(other:FinanceDecimal|number|string|bigint){return new FinanceDecimal(this.raw-FinanceDecimal.from(other).raw)}
 multiply(other:FinanceDecimal|number|string|bigint){return new FinanceDecimal(divRound(this.raw*FinanceDecimal.from(other).raw,SCALE))}
 divide(other:FinanceDecimal|number|string|bigint){const d=FinanceDecimal.from(other).raw;return new FinanceDecimal(divRound(this.raw*SCALE,d))}
 negate(){return new FinanceDecimal(-this.raw)} abs(){return new FinanceDecimal(abs(this.raw))}
 compare(other:FinanceDecimal|number|string|bigint){const b=FinanceDecimal.from(other).raw;return this.raw===b?0:this.raw<b?-1:1}
 isInteger(){return this.raw%SCALE===0n}
 toSafeInteger(){if(!this.isInteger())throw new RangeError('An exact integer decimal was required.');const value=this.raw/SCALE;if(value>BigInt(Number.MAX_SAFE_INTEGER)||value<BigInt(Number.MIN_SAFE_INTEGER))throw new RangeError('Integer value exceeds the safe JavaScript integer range.');return Number(value)}
 powInt(exponent:number):FinanceDecimal{if(!Number.isInteger(exponent))throw new RangeError('Integer power expected.');if(exponent===0)return FinanceDecimal.one();if(exponent<0)return FinanceDecimal.one().divide(this.powInt(-exponent));let result:FinanceDecimal=FinanceDecimal.one(),base:FinanceDecimal=this,e=exponent;while(e>0){if(e%2===1)result=result.multiply(base);e=Math.floor(e/2);if(e)base=base.multiply(base);}return result}
 rootInt(n:number):FinanceDecimal{if(!Number.isInteger(n)||n<=0||n>10_000)throw new RangeError('Root degree must be a positive integer not exceeding 10,000.');if(n===1)return this;if(this.raw<0n&&n%2===0)throw new RangeError('Even root of a negative value is not real.');if(this.raw===0n)return FinanceDecimal.zero();const negative=this.raw<0n;const target=negative?this.negate():this;const digits=target.raw.toString().length;const decimalExponent=digits-1-SCALE_DIGITS;const rootExponent=Math.floor(decimalExponent/n);let guessRaw=rootExponent>=0?SCALE*10n**BigInt(rootExponent):SCALE/10n**BigInt(-rootExponent);if(guessRaw<=0n)guessRaw=1n;let guess=new FinanceDecimal(guessRaw);for(let i=0;i<96;i++){const denom=guess.powInt(n-1);if(denom.raw===0n)throw new RangeError('Root iteration lost fixed-point resolution.');const next=guess.multiply(n-1).add(target.divide(denom)).divide(n);if(abs(next.raw-guess.raw)<=1n){guess=next;break}guess=next;if(i===95)throw new RangeError('Root iteration did not converge at the configured fixed-point precision.');}return negative?guess.negate():guess}
 toBoundedFraction(maxDenominator=10_000):{numerator:bigint;denominator:bigint;exact:boolean}{if(!Number.isSafeInteger(maxDenominator)||maxDenominator<1)throw new RangeError('Maximum denominator must be a positive safe integer.');const sign=this.raw<0n?-1n:1n;const target=abs(this.raw);let n=target,d=SCALE;let h0=0n,h1=1n,k0=1n,k1=0n;const limit=BigInt(maxDenominator);while(d!==0n){const a=n/d;const h2=a*h1+h0,k2=a*k1+k0;if(k2>limit){const t=k1===0n?0n:(limit-k0)/k1;const hc=t*h1+h0,kc=t*k1+k0;if(kc===0n)return{numerator:sign*h1,denominator:k1,exact:false};const errC=abs(target*kc-hc*SCALE),errPrev=abs(target*k1-h1*SCALE);const chooseC=errC*k1<=errPrev*kc;const numerator=chooseC?hc:h1,denominator=chooseC?kc:k1;return{numerator:sign*numerator,denominator,exact:false};}h0=h1;h1=h2;k0=k1;k1=k2;const remainder=n%d;if(remainder===0n)return{numerator:sign*h1,denominator:k1,exact:true};n=d;d=remainder;}return{numerator:sign*h1,denominator:k1,exact:true}}
 powFraction(numerator:bigint,denominator:bigint):FinanceDecimal{if(denominator===0n)throw new RangeError('Fractional exponent denominator cannot be zero.');if(denominator<0n){numerator=-numerator;denominator=-denominator;}const g=gcd(numerator,denominator);numerator/=g;denominator/=g;if(denominator>10_000n)throw new RangeError('Fractional exponent denominator exceeds the supported fixed-point root degree of 10,000.');if(abs(numerator)>10_000n)throw new RangeError('Fractional exponent numerator exceeds the supported magnitude of 10,000.');if(numerator===0n)return FinanceDecimal.one();const powered=this.powInt(Number(abs(numerator)));const rooted=powered.rootInt(Number(denominator));return numerator<0n?FinanceDecimal.one().divide(rooted):rooted}
 powRational(exponent:number):FinanceDecimal{if(!Number.isFinite(exponent))throw new RangeError('Exponent must be finite.');if(Number.isInteger(exponent))return this.powInt(exponent);const fraction=FinanceDecimal.from(String(exponent)).toBoundedFraction();return this.powFraction(fraction.numerator,fraction.denominator)}
 toNumber(){return Number(this.raw)/Number(SCALE)}
 toString(maxPlaces=SCALE_DIGITS){const neg=this.raw<0n;const raw=abs(this.raw);const whole=raw/SCALE;let frac=(raw%SCALE).toString().padStart(SCALE_DIGITS,'0').slice(0,Math.max(0,Math.min(SCALE_DIGITS,maxPlaces))).replace(/0+$/,'');return `${neg?'-':''}${whole}${frac?'.'+frac:''}`}
 toFixed(places:number){if(!Number.isInteger(places)||places<0||places>SCALE_DIGITS)throw new RangeError(`Decimal places must be between 0 and ${SCALE_DIGITS}.`);const factor=10n**BigInt(SCALE_DIGITS-places);const rounded=divRound(this.raw,factor);const neg=rounded<0n;const raw=abs(rounded);const base=10n**BigInt(places);const whole=raw/base;const frac=places?(raw%base).toString().padStart(places,'0'):'';return`${neg?'-':''}${whole}${places?'.'+frac:''}`}
}
