import type { AnnuityTiming, Cashflow, FinanceResult, FinanceScalar, FinanceTraceStep, NumericCertainty, ValueDirection } from './types.ts';
import { FINANCE_SCALE_DIGITS, FinanceDecimal as D } from './decimal.ts';

export const MAX_FINANCE_INTEGER_PERIODS=10_000;
export const FINANCE_ROUNDING_MODE='half-up' as const;
export const BOND_CLASSIFICATION_POLICY='legacy-relative-tolerance' as const;
const FIXED:NumericCertainty='fixed-point-rounded';
const APPROX:NumericCertainty='iterative-approximation';

function decimal(name:string,value:FinanceScalar):D{
 try{return D.from(value)}catch(error){throw new RangeError(`${name} must be a finite decimal value. ${error instanceof Error?error.message:''}`.trim())}
}
function nonnegative(name:string,value:FinanceScalar):D{const parsed=decimal(name,value);if(parsed.compare(0)<0)throw new RangeError(`${name} cannot be negative.`);return parsed}
function validRate(rate:FinanceScalar):D{const parsed=decimal('Rate',rate);if(parsed.compare(-1)<=0)throw new RangeError('The effective rate must be greater than -100%.');return parsed}
function validFrequency(value:number|string,label='Compounding frequency'):number{
 const text=String(value).trim();if(!/^\d+$/.test(text))throw new RangeError(`${label} must be a positive integer.`);const parsed=Number(text);if(!Number.isSafeInteger(parsed)||parsed<=0)throw new RangeError(`${label} must be a positive safe integer.`);if(parsed>MAX_FINANCE_INTEGER_PERIODS)throw new RangeError(`${label} cannot exceed ${MAX_FINANCE_INTEGER_PERIODS}.`);return parsed;
}
function nonnegativeInteger(value:number|string,label:string):number{
 const text=String(value).trim();if(!/^\d+$/.test(text))throw new RangeError(`${label} must be a nonnegative integer.`);const parsed=Number(text);if(!Number.isSafeInteger(parsed)||parsed<0)throw new RangeError(`${label} must be a nonnegative safe integer.`);if(parsed>MAX_FINANCE_INTEGER_PERIODS)throw new RangeError(`${label} cannot exceed ${MAX_FINANCE_INTEGER_PERIODS}.`);return parsed;
}
function normalizeTrace(trace:FinanceTraceStep[]):FinanceTraceStep[]{return trace.map(step=>step.decimalValue||!step.exactValue?step:{...step,decimalValue:step.exactValue});}
function result(value:D,trace:FinanceTraceStep[],certainty:NumericCertainty=FIXED,warnings:string[]=[]):FinanceResult{
 const decimalValue=value.toString();
 return{value:value.toNumber(),decimalValue,exactValue:decimalValue,certainty,precisionDigits:FINANCE_SCALE_DIGITS,roundingMode:FINANCE_ROUNDING_MODE,warnings:warnings.length?warnings:undefined,trace:normalizeTrace(trace)};
}
function exponentCertainty(exponent:D):NumericCertainty{return exponent.isInteger()?FIXED:APPROX}
function mergeCertainty(left:NumericCertainty,right:NumericCertainty):NumericCertainty{return left===APPROX||right===APPROX?APPROX:left==='fixed-point-rounded'||right==='fixed-point-rounded'?FIXED:'exact'}
function powForFinance(base:D,exponent:D):{value:D;certainty:NumericCertainty}{if(exponent.isInteger()){const integer=exponent.toSafeInteger();if(Math.abs(integer)>MAX_FINANCE_INTEGER_PERIODS)throw new RangeError(`Integer finance exponents cannot exceed ${MAX_FINANCE_INTEGER_PERIODS} periods in magnitude.`);return{value:base.powInt(integer),certainty:FIXED}}const fraction=exponent.toBoundedFraction(MAX_FINANCE_INTEGER_PERIODS);return{value:base.powFraction(fraction.numerator,fraction.denominator),certainty:APPROX}}

export function roundFinance(value:number,places=4):number{const factor=10**places;return Math.round((value+Number.EPSILON)*factor)/factor}
export function formatFinanceDecimal(value:FinanceResult|D,places=12):string{return value instanceof D?value.toString(places):D.from(value.decimalValue).toString(places)}
/** @deprecated Compatibility name. The returned text is fixed-point/approximate according to result.certainty. */
export function formatFinanceExact(value:FinanceResult|D,places=12):string{return formatFinanceDecimal(value,places)}

export function simpleAccumulation(principal:FinanceScalar,annualRate:FinanceScalar,years:FinanceScalar):FinanceResult{
 const p=nonnegative('Principal',principal),i=validRate(annualRate),t=nonnegative('Time',years),factor=D.one().add(i.multiply(t)),value=p.multiply(factor);
 const warnings=factor.compare(0)<=0?['The algebraic simple-interest factor is nonpositive. The course-mode policy for this edge case is unresolved (D-001); interpret this result as an algebraic model value, not an endorsed financial scenario.']:[];
 return result(value,[{id:'identify',label:'Identify the simple-interest model',expression:'A = P(1 + it)',explanation:'Simple interest is earned only on the original principal.'},{id:'factor',label:'Build the accumulation factor',expression:`1 + (${annualRate})(${years}) = ${factor.toString(12)}`,explanation:'Multiply the annual rate by elapsed years, then add 1.',value:factor.toNumber(),exactValue:factor.toString()},{id:'accumulate',label:'Accumulate the principal',expression:`${principal}(${factor.toString(12)}) = ${value.toString(12)}`,explanation:'Scale the original principal by the simple-interest accumulation factor.',value:value.toNumber(),exactValue:value.toString()}],FIXED,warnings);
}
export function compoundAccumulation(principal:FinanceScalar,annualEffectiveRate:FinanceScalar,years:FinanceScalar):FinanceResult{
 const p=nonnegative('Principal',principal),i=validRate(annualEffectiveRate),t=nonnegative('Time',years),base=D.one().add(i),power=powForFinance(base,t),value=p.multiply(power.value);
 return result(value,[{id:'identify',label:'Identify the compound model',expression:'A = P(1 + i)^t',explanation:'Compound interest earns interest on the accumulated balance.'},{id:'factor',label:'Build the accumulation factor',expression:`(1 + ${annualEffectiveRate})^${years} = ${power.value.toString(12)}`,explanation:'Raise the one-period accumulation factor to the elapsed number of periods.',value:power.value.toNumber(),exactValue:power.value.toString()},{id:'accumulate',label:'Accumulate the principal',expression:`${principal}(${power.value.toString(12)}) = ${value.toString(12)}`,explanation:'Multiply principal by the compound accumulation factor.',value:value.toNumber(),exactValue:value.toString()}],power.certainty);
}
export function nominalAccumulation(principal:FinanceScalar,nominalAnnualRate:FinanceScalar,m:number|string,years:FinanceScalar):FinanceResult{
 const p=nonnegative('Principal',principal),j=decimal('Nominal rate',nominalAnnualRate),frequency=validFrequency(m),t=nonnegative('Time',years),periodic=j.divide(frequency);if(D.one().add(periodic).compare(0)<=0)throw new RangeError('The rate per conversion period must keep the accumulation factor positive.');const periods=D.from(frequency).multiply(t),power=powForFinance(D.one().add(periodic),periods),value=p.multiply(power.value);
 return result(value,[{id:'periodic',label:'Convert the nominal rate to a periodic rate',expression:`j/m = ${nominalAnnualRate}/${frequency} = ${periodic.toString(12)}`,explanation:'A nominal annual rate is divided by its number of conversion periods.',value:periodic.toNumber(),exactValue:periodic.toString()},{id:'periods',label:'Count conversion periods',expression:`mt = ${frequency}(${years}) = ${periods.toString(8)}`,explanation:'Compounding occurs once per conversion period.',value:periods.toNumber(),exactValue:periods.toString()},{id:'accumulate',label:'Compound over all conversion periods',expression:`A = ${principal}(1 + ${periodic.toString(12)})^${periods.toString(8)} = ${value.toString(12)}`,explanation:'Use the periodic rate for every conversion period.',value:value.toNumber(),exactValue:value.toString()}],power.certainty);
}
export function nominalToEffective(nominalAnnualRate:FinanceScalar,m:number|string):FinanceResult{
 const j=decimal('Nominal rate',nominalAnnualRate),frequency=validFrequency(m),periodic=j.divide(frequency);if(D.one().add(periodic).compare(0)<=0)throw new RangeError('The periodic accumulation factor must be positive.');const value=D.one().add(periodic).powInt(frequency).subtract(1);return result(value,[{id:'periodic',label:'Periodic rate',expression:`j/m = ${nominalAnnualRate}/${frequency} = ${periodic.toString(12)}`,explanation:'Divide the quoted nominal annual rate by the conversion frequency.',value:periodic.toNumber(),exactValue:periodic.toString()},{id:'annualize',label:'Equivalent annual effective rate',expression:`i = (1 + ${periodic.toString(12)})^${frequency} - 1 = ${value.toString(12)}`,explanation:'Equivalent rates produce the same one-year accumulation.',value:value.toNumber(),exactValue:value.toString()}],FIXED);
}
export function effectiveToNominal(annualEffectiveRate:FinanceScalar,m:number|string):FinanceResult{
 const i=validRate(annualEffectiveRate),frequency=validFrequency(m),periodic=D.one().add(i).rootInt(frequency).subtract(1),value=periodic.multiply(frequency),certainty=frequency===1?FIXED:APPROX;return result(value,[{id:'periodic',label:'Equivalent periodic rate',expression:`(1 + i)^(1/${frequency}) - 1 = ${periodic.toString(12)}`,explanation:'Find the conversion-period rate that reproduces the same annual accumulation.',value:periodic.toNumber(),exactValue:periodic.toString()},{id:'quote',label:'Nominal annual quote',expression:`j = ${frequency}(${periodic.toString(12)}) = ${value.toString(12)}`,explanation:'Multiply the periodic rate by the number of conversion periods.',value:value.toNumber(),exactValue:value.toString()}],certainty);
}
export function valueAtTime(amount:FinanceScalar,fromTime:FinanceScalar,toTime:FinanceScalar,annualEffectiveRate:FinanceScalar):FinanceResult{
 const a=decimal('Amount',amount),from=decimal('Starting time',fromTime),to=decimal('Valuation time',toTime),i=validRate(annualEffectiveRate),periods=to.subtract(from),power=powForFinance(D.one().add(i),periods),value=a.multiply(power.value),direction=periods.compare(0)>=0?'accumulate':'discount';return result(value,[{id:'distance',label:'Measure the time shift',expression:`${toTime} - ${fromTime} = ${periods.toString(12)}`,explanation:'Cash flows must be moved to one common focal date before they can be compared.',value:periods.toNumber(),exactValue:periods.toString()},{id:'move',label:direction==='accumulate'?'Accumulate forward':'Discount backward',expression:`${amount}(1 + ${annualEffectiveRate})^${periods.toString(12)} = ${value.toString(12)}`,explanation:direction==='accumulate'?'Moving right on the timeline multiplies by accumulation factors.':'Moving left on the timeline divides by accumulation factors.',value:value.toNumber(),exactValue:value.toString()}],power.certainty);
}
export function valueCashflowsAt(cashflows:Cashflow[],valuationTime:FinanceScalar,annualEffectiveRate:FinanceScalar):FinanceResult{
 if(cashflows.length===0)throw new RangeError('At least one cash flow is required.');const i=validRate(annualEffectiveRate),valuation=decimal('Valuation time',valuationTime);const trace:FinanceTraceStep[]=[];let value=D.zero(),certainty:NumericCertainty=FIXED;cashflows.forEach((flow,index)=>{const time=decimal('Cash-flow time',flow.time),amount=decimal('Cash-flow amount',flow.amount),periods=valuation.subtract(time),power=powForFinance(D.one().add(i),periods),moved=amount.multiply(power.value);certainty=mergeCertainty(certainty,power.certainty);value=value.add(moved);trace.push({id:`flow-${index}`,label:flow.label||`Cash flow ${index+1}`,expression:`${flow.amount}(1 + ${annualEffectiveRate})^(${valuationTime} - ${flow.time}) = ${moved.toString(12)}`,explanation:'Move this cash flow to the common focal date before adding it.',value:moved.toNumber(),exactValue:moved.toString()})});trace.push({id:'sum',label:'Combine values at the focal date',expression:`V(${valuationTime}) = ${value.toString(12)}`,explanation:'Amounts may be added only after they refer to the same valuation date.',value:value.toNumber(),exactValue:value.toString()});return result(value,trace,certainty);
}
function annuityFactor(rate:FinanceScalar,n:number|string,direction:ValueDirection):D{const i=validRate(rate),count=nonnegativeInteger(n,'The number of payments');if(count===0)return D.zero();if(i.compare(0)===0)return D.from(count);const base=D.one().add(i);return direction==='present'?D.one().subtract(base.powInt(-count)).divide(i):base.powInt(count).subtract(1).divide(i)}
export function annuityValue(payment:FinanceScalar,ratePerPaymentPeriod:FinanceScalar,n:number|string,timing:AnnuityTiming,direction:ValueDirection):FinanceResult{
 const pay=decimal('Payment',payment),count=nonnegativeInteger(n,'The number of payments'),rate=validRate(ratePerPaymentPeriod),base=annuityFactor(ratePerPaymentPeriod,count,direction),timingFactor=timing==='due'?D.one().add(rate):D.one(),unit=base.multiply(timingFactor),value=pay.multiply(unit),symbol=direction==='present'?'a-angle-n':'s-angle-n',baseExpr=rate.compare(0)===0?`${count}`:direction==='present'?'(1 - (1+i)^(-n))/i':'((1+i)^n - 1)/i';return result(value,[{id:'base',label:`${direction==='present'?'Present':'Future'}-value annuity factor`,expression:`${symbol} = ${baseExpr} = ${base.toString(12)}`,explanation:`This factor combines ${count} equal ${timing==='immediate'?'end-of-period':'beginning-of-period'} payments at one focal date.`,value:base.toNumber(),exactValue:base.toString()},...(timing==='due'?[{id:'due',label:'Shift an annuity-immediate one period',expression:`factor × (1 + i) = ${unit.toString(12)}`,explanation:'Every annuity-due payment occurs one period earlier, so the entire value is one accumulation factor larger.',value:unit.toNumber(),exactValue:unit.toString()}]:[]),{id:'payment',label:'Scale by the payment amount',expression:`${payment} × ${unit.toString(12)} = ${value.toString(12)}`,explanation:'The annuity factor is the value of unit payments; multiply by the actual payment.',value:value.toNumber(),exactValue:value.toString()}],FIXED);
}
export function annuityPaymentForValue(targetValue:FinanceScalar,rate:FinanceScalar,n:number|string,timing:AnnuityTiming,direction:ValueDirection):FinanceResult{const target=decimal('Target value',targetValue),unit=annuityValue('1',rate,n,timing,direction);if(D.from(unit.decimalValue).compare(0)===0)throw new RangeError('The annuity factor is zero, so a payment cannot be solved.');const value=target.divide(unit.decimalValue);return result(value,[...unit.trace,{id:'solve-payment',label:'Solve for the level payment',expression:`R = ${targetValue} / ${unit.decimalValue} = ${value.toString(12)}`,explanation:'Divide the target value by the value of one unit payment.',value:value.toNumber(),exactValue:value.toString()}],unit.certainty)}
export type BondClassificationPolicy=typeof BOND_CLASSIFICATION_POLICY;
export type BondPriceResult=FinanceResult&{couponPayment:number;redemptionPresentValue:number;couponPresentValue:number;classification:'premium'|'discount'|'par';classificationPolicy:BondClassificationPolicy;classificationTolerance:string};
export function bondPrice(input:{faceValue:FinanceScalar;couponRatePerPeriod:FinanceScalar;redemptionValue:FinanceScalar;yieldPerPeriod:FinanceScalar;periods:number|string}):BondPriceResult{
 const{faceValue,couponRatePerPeriod,redemptionValue,yieldPerPeriod}=input,periods=nonnegativeInteger(input.periods,'Coupon periods');if(periods<=0)throw new RangeError('Coupon periods must be a positive integer.');const face=nonnegative('Face value',faceValue),redemption=nonnegative('Redemption value',redemptionValue),couponRate=decimal('Coupon rate',couponRatePerPeriod),yieldRate=validRate(yieldPerPeriod),couponPayment=face.multiply(couponRate),discount=D.one().add(yieldRate).powInt(-periods),factor=yieldRate.compare(0)===0?D.from(periods):D.one().subtract(discount).divide(yieldRate),couponPV=couponPayment.multiply(factor),redemptionPV=redemption.multiply(discount),value=couponPV.add(redemptionPV),difference=value.subtract(redemption),toleranceBase=redemption.abs().compare(1)>0?redemption.abs():D.one(),tolerance=toleranceBase.multiply('0.0000000001'),classification=difference.compare(tolerance)>0?'premium':difference.compare(tolerance.negate())<0?'discount':'par';return{...result(value,[{id:'coupon',label:'Find the coupon payment',expression:`Fr = ${faceValue}(${couponRatePerPeriod}) = ${couponPayment.toString(12)}`,explanation:'The face value and coupon rate per coupon period determine each level coupon.',value:couponPayment.toNumber(),exactValue:couponPayment.toString()},{id:'coupons',label:'Value the coupon stream',expression:`(Fr)a_n|j = ${couponPayment.toString(12)}(${factor.toString(12)}) = ${couponPV.toString(12)}`,explanation:'The coupons form an annuity-immediate valued at the bond yield per coupon period.',value:couponPV.toNumber(),exactValue:couponPV.toString()},{id:'redemption',label:'Discount the redemption value',expression:`Cv^n = ${redemptionValue}(1 + ${yieldPerPeriod})^(-${periods}) = ${redemptionPV.toString(12)}`,explanation:'The redemption amount is a single future cash flow at maturity.',value:redemptionPV.toNumber(),exactValue:redemptionPV.toString()},{id:'price',label:'Combine all values at the purchase date',expression:`P = ${couponPV.toString(12)} + ${redemptionPV.toString(12)} = ${value.toString(12)}`,explanation:'Bond price is the present value of all coupons plus the present value of redemption.',value:value.toNumber(),exactValue:value.toString()}],FIXED),couponPayment:couponPayment.toNumber(),couponPresentValue:couponPV.toNumber(),redemptionPresentValue:redemptionPV.toNumber(),classification,classificationPolicy:BOND_CLASSIFICATION_POLICY,classificationTolerance:tolerance.toString()};
}
