import AxeBuilder from '@axe-core/playwright'; import { expect, test } from '@playwright/test';
const routes=['/modules/finance','/modules/linear','/modules/applications','/labs/interest','/labs/annuity','/labs/bonds','/labs/matrix-operations','/labs/row-reduction','/labs/linear-programming','/labs/game-theory','/labs/probability-simulation'];
const labRoutes=['/labs/annuity','/labs/bayes','/labs/bonds','/labs/cashflow-timeline','/labs/conditional-probability','/labs/counting','/labs/distribution','/labs/equivalence','/labs/formal-proof','/labs/game-theory','/labs/interest','/labs/linear-programming','/labs/logic-basics','/labs/markov','/labs/matrix-operations','/labs/probability-simulation','/labs/row-reduction','/labs/truth-table'];

test('@core every lab uses the shared context shell',async({page})=>{for(const route of labRoutes){await page.goto(route);await expect(page.locator('[data-lab-shell]'),route).toHaveCount(1);await expect(page.locator('.lab-route__workspace'),route).toBeVisible();await expect(page.getByRole('navigation',{name:'Breadcrumb'}).getByRole('link',{name:'Home'}),route).toBeVisible();}});
for(const route of routes){test(`@core ${route} renders without page overflow`,async({page})=>{await page.goto(route);await expect(page.locator('main')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);});}
test('@core finance compound model updates deterministic result',async({page})=>{await page.goto('/labs/interest');const lab=page.getByTestId('interest-lab');await expect(lab).toBeVisible();await expect(lab.getByText(/Accumulated value/)).toBeVisible();});
test('@core annuity timing can switch to due',async({page})=>{await page.goto('/labs/annuity');const lab=page.getByTestId('annuity-lab');await expect(lab).toHaveAttribute('data-hydrated','true');await lab.getByRole('button',{name:/Due/}).click();await expect(lab.getByText(/beginning of each period/i)).toBeVisible();});
test('@core matrix multiplication exposes selected dot product',async({page})=>{await page.goto('/labs/matrix-operations');const lab=page.getByTestId('matrix-operations-lab');await expect(lab.getByText(/Row 1 · Column 1/)).toBeVisible();await expect(lab.getByText(/Sum =/)).toBeVisible();});
test('@core row reduction exposes unique solution',async({page})=>{await page.goto('/labs/row-reduction');const lab=page.getByTestId('row-reduction-lab');await expect(lab.locator('.formula-callout').getByText('unique',{exact:true})).toBeVisible();});
test('@core graphical LP and simplex agree on sample optimum',async({page})=>{await page.goto('/labs/linear-programming');const lab=page.getByTestId('lp-lab');await expect(lab.locator('.lp-lab__visual .formula-callout strong')).toHaveText('optimal');await expect(lab.getByText(/Z = 11/)).toBeVisible();});
test('@core game theory default requires mixed strategy',async({page})=>{await page.goto('/labs/game-theory');const lab=page.getByTestId('game-theory-lab');await expect(lab.getByText(/Row mix/)).toBeVisible();});
test('new course routes have no serious axe findings',async({page})=>{for(const route of ['/labs/interest','/labs/matrix-operations','/labs/linear-programming','/labs/game-theory','/labs/probability-simulation']){await page.goto(route);const results=await new AxeBuilder({page}).analyze();expect(results.violations.filter(v=>['critical','serious'].includes(v.impact??'')),route).toEqual([]);}});
