import AxeBuilder from '@axe-core/playwright'; import { expect, test } from '@playwright/test';
const routes=['/modules/finance','/modules/linear','/modules/applications','/labs/interest','/labs/annuity','/labs/bonds','/labs/matrix-operations','/labs/row-reduction','/labs/linear-programming','/labs/game-theory','/labs/probability-simulation'];
for(const route of routes){test(`@core ${route} renders without page overflow`,async({page})=>{await page.goto(route);await expect(page.locator('main')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);});}
test('@core finance compound model updates deterministic result',async({page})=>{await page.goto('/labs/interest');const lab=page.getByTestId('interest-lab');await expect(lab).toBeVisible();await expect(lab.getByText(/Accumulated value/)).toBeVisible();});
test('@core annuity timing can switch to due',async({page})=>{await page.goto('/labs/annuity','/labs/bonds');const lab=page.getByTestId('annuity-lab');await lab.getByRole('button',{name:/Due/}).click();await expect(lab.getByText(/beginning of each period/i)).toBeVisible();});
test('@core matrix multiplication exposes selected dot product',async({page})=>{await page.goto('/labs/matrix-operations');const lab=page.getByTestId('matrix-operations-lab');await expect(lab.getByText(/Row 1 · Column 1/)).toBeVisible();await expect(lab.getByText(/Sum =/)).toBeVisible();});
test('@core row reduction exposes unique solution',async({page})=>{await page.goto('/labs/row-reduction');const lab=page.getByTestId('row-reduction-lab');await expect(lab.getByText('unique',{exact:true})).toBeVisible();});
test('@core graphical LP and simplex agree on sample optimum',async({page})=>{await page.goto('/labs/linear-programming');const lab=page.getByTestId('lp-lab');await expect(lab.getByText('optimal',{exact:true})).toBeVisible();await expect(lab.getByText(/Z = 11/)).toBeVisible();});
test('@core game theory default requires mixed strategy',async({page})=>{await page.goto('/labs/game-theory','/labs/probability-simulation');const lab=page.getByTestId('game-theory-lab');await expect(lab.getByText(/Row mix/)).toBeVisible();});
test('new course routes have no serious axe findings',async({page})=>{for(const route of ['/labs/interest','/labs/matrix-operations','/labs/linear-programming','/labs/game-theory','/labs/probability-simulation']){await page.goto(route);const results=await new AxeBuilder({page}).analyze();expect(results.violations.filter(v=>['critical','serious'].includes(v.impact??'')),route).toEqual([]);}});
