import { useMemo, useState } from 'react';
import { addMatrices, determinant, matrix, matrixToStrings, multiplicationCellTrace, multiplyMatrices, shape, transpose, type Matrix } from '@amat19/domain-linear';
import { Button } from '../../ui/Button';import { Feedback } from '../../ui/Feedback';import { recordAttempt,recordSkillEvidence } from '../../../lib/local-progress';
type Operation='add'|'multiply'|'transpose-a'|'determinant-a';
function parseGrid(raw:string):Matrix{const rows=raw.trim().split(/\n+/).map(line=>line.trim().split(/[\s,]+/).filter(Boolean));if(rows.length===0||rows[0]!.length===0)throw new Error('Enter at least one matrix row.');return matrix(rows);}
function MatrixTable({value,onCell,selected}:{value:Matrix;onCell?:(r:number,c:number)=>void;selected?:[number,number]}){return <div className="matrix-wrap"><table className="matrix-table"><tbody>{value.map((row,r)=><tr key={r}>{row.map((v,c)=><td key={c}>{onCell?<button className="matrix-cell-button" data-selected={selected?.[0]===r&&selected?.[1]===c} onClick={()=>onCell(r,c)}>{v.toString()}</button>:v.toString()}</td>)}</tr>)}</tbody></table></div>}
export default function MatrixOperationsLab(){const[aRaw,setARaw]=useState('1 2\n3 4'),[bRaw,setBRaw]=useState('2 0\n1 2'),[operation,setOperation]=useState<Operation>('multiply'),[selected,setSelected]=useState<[number,number]>([0,0]),[prediction,setPrediction]=useState<'compatible'|'incompatible'>(),[checked,setChecked]=useState(false);
 const analysis=useMemo(()=>{try{const A=parseGrid(aRaw),B=parseGrid(bRaw),sa=shape(A),sb=shape(B);let result:Matrix|undefined,scalar:string|undefined;if(operation==='add')result=addMatrices(A,B);if(operation==='multiply')result=multiplyMatrices(A,B);if(operation==='transpose-a')result=transpose(A);if(operation==='determinant-a')scalar=determinant(A).toString();const trace=operation==='multiply'&&result?multiplicationCellTrace(A,B,Math.min(selected[0],result.length-1),Math.min(selected[1],result[0]!.length-1)):undefined;return{A,B,sa,sb,result,scalar,trace,error:undefined};}catch(e){return{error:e instanceof Error?e.message:'Matrix input could not be evaluated.'};}},[aRaw,bRaw,operation,selected]);
 async function checkCompatibility(){if(!analysis.sa||!analysis.sb||!prediction)return;const compatible=operation==='add'?analysis.sa.rows===analysis.sb.rows&&analysis.sa.cols===analysis.sb.cols:analysis.sa.cols===analysis.sb.rows;const ok=(prediction==='compatible')===compatible;setChecked(true);await Promise.all([recordAttempt({prefix:'matrix',exerciseId:'linear.matrix.compatibility',module:'linear',finalState:ok?'correct':'incomplete',payload:{operation,prediction,shapeA:analysis.sa,shapeB:analysis.sb}}),recordSkillEvidence('linear.operations',ok?1:0)]).catch(()=>undefined);}
 return <section className="matrix-lab" data-testid="matrix-operations-lab"><div className="matrix-lab__inputs"><p className="section-label">Matrix operations</p><h2>Dimensions decide what operation is legal.</h2><div className="view-switch">{(['add','multiply','transpose-a','determinant-a'] as Operation[]).map(op=><Button key={op} variant={operation===op?'primary':'secondary'} onClick={()=>{setOperation(op);setChecked(false)}}>{op==='transpose-a'?'Transpose A':op==='determinant-a'?'det(A)':op[0]!.toUpperCase()+op.slice(1)}</Button>)}</div><div className="matrix-input-pair"><label className="form-field"><span className="form-field__label">Matrix A · rows separated by new lines</span><textarea className="matrix-textarea" rows={4} value={aRaw} onChange={e=>setARaw(e.target.value)}/></label>{(operation==='add'||operation==='multiply')&&<label className="form-field"><span className="form-field__label">Matrix B</span><textarea className="matrix-textarea" rows={4} value={bRaw} onChange={e=>setBRaw(e.target.value)}/></label>}</div>{(operation==='add'||operation==='multiply')&&<fieldset className="prediction-fieldset"><legend>Predict compatibility before calculating</legend><label><input type="radio" checked={prediction==='compatible'} onChange={()=>{setPrediction('compatible');setChecked(false)}}/> The operation is defined</label><label><input type="radio" checked={prediction==='incompatible'} onChange={()=>{setPrediction('incompatible');setChecked(false)}}/> The dimensions make it undefined</label><Button disabled={!prediction||!analysis.sa||!analysis.sb} onClick={checkCompatibility}>Check dimensions</Button>{checked&&analysis.sa&&analysis.sb&&<Feedback tone={((prediction==='compatible')===(operation==='add'?analysis.sa.rows===analysis.sb.rows&&analysis.sa.cols===analysis.sb.cols:analysis.sa.cols===analysis.sb.rows))?'success':'error'}>A is {analysis.sa.rows}×{analysis.sa.cols}; B is {analysis.sb.rows}×{analysis.sb.cols}. {operation==='add'?'Addition needs equal dimensions.':'Multiplication needs inner dimensions to match.'}</Feedback>}</fieldset>}</div>
 <div className="matrix-lab__visual">{analysis.error?<Feedback tone="error" role="alert">{analysis.error}</Feedback>:<><div className="matrix-equation"><div><span>A</span><MatrixTable value={analysis.A!}/></div>{(operation==='add'||operation==='multiply')&&<><strong>{operation==='add'?'+':'×'}</strong><div><span>B</span><MatrixTable value={analysis.B!}/></div></>}<strong>=</strong><div><span>{operation==='determinant-a'?'det(A)':'result'}</span>{analysis.result?<MatrixTable value={analysis.result} selected={selected} onCell={operation==='multiply'?(r,c)=>setSelected([r,c]):undefined}/>:<div className="scalar-result">{analysis.scalar}</div>}</div></div>{analysis.trace&&<div className="dot-product-trace"><p className="section-label">Selected product cell</p><strong>Row {analysis.trace.row+1} · Column {analysis.trace.col+1}</strong><div>{analysis.trace.terms.map((t,i)=><span key={i}>{t.left.toString()} × {t.right.toString()} = {t.product.toString()}</span>)}</div><p>Sum = <strong>{analysis.trace.value.toString()}</strong></p></div>}</>}</div></section>}
