import { useEffect, useMemo, useState } from 'react';
import { applyRowOperation, identity, inverse, matricesEqual, matrix, rref, solveLinearSystem, type Matrix, type RowOperation } from '@amat19/domain-linear';
import { Button } from '../../ui/Button';import { Feedback } from '../../ui/Feedback';import { Badge } from '../../ui/Badge';import { MatrixEditor } from '../../math/MatrixEditor';import { MatrixView } from '../../math/MatrixView';import { recordAttempt,recordSkillEvidence } from '../../../lib/local-progress';
type Mode='system'|'inverse'|'rref';type Workspace='guided'|'manual';type ManualStep={operation:RowOperation;matrix:Matrix};
function parse(raw:string):Matrix{return matrix(raw.trim().split(/\n+/).map(line=>line.trim().split(/[\s,]+/).filter(Boolean)))}
function manualInitial(M:Matrix,mode:Mode):Matrix{if(mode!=='inverse')return M;const I=identity(M.length);if(M.some(row=>row.length!==M.length))throw new Error('Inverse mode requires a square matrix.');return M.map((row,r)=>[...row,...I[r]!])}
export default function RowReductionLab(){
 const[mode,setMode]=useState<Mode>('system'),[workspace,setWorkspace]=useState<Workspace>('guided'),[raw,setRaw]=useState('1 1 3\n1 -1 1'),[step,setStep]=useState(0),[prediction,setPrediction]=useState<'unique'|'infinite'|'inconsistent'>(),[checked,setChecked]=useState(false);const[manual,setManual]=useState<Matrix>();const[manualHistory,setManualHistory]=useState<ManualStep[]>([]);const[opKind,setOpKind]=useState<'swap'|'scale'|'replace'>('replace'),[rowA,setRowA]=useState(1),[rowB,setRowB]=useState(2),[factor,setFactor]=useState('-1'),[manualMessage,setManualMessage]=useState<string>();
 const out=useMemo(()=>{try{const M=parse(raw);if(mode==='system'){const result=solveLinearSystem(M);return{M,result,steps:result.steps,final:result.rref,error:undefined}}if(mode==='inverse'){const result=inverse(M);return{M,result,steps:result?.steps??[],final:result?.inverse,error:result?undefined:'This matrix is singular, so the left block cannot become identity.'}}const result=rref(M);return{M,result,steps:result.steps,final:result.matrix,error:undefined}}catch(error){return{error:error instanceof Error?error.message:'Could not row-reduce this matrix.'}}},[raw,mode]);
 useEffect(()=>{if(!out.M)return;try{setManual(manualInitial(out.M,mode));setManualHistory([]);setManualMessage(undefined)}catch{setManual(undefined)}},[raw,mode]);
 const display=step===0?out.M:out.steps?.[Math.min(step-1,(out.steps?.length??1)-1)]?.after;const manualTarget=useMemo(()=>manual?(()=>{try{return rref(manualInitial(parse(raw),mode)).matrix}catch{return undefined}})():undefined,[raw,mode,manual]);const manualComplete=manual&&manualTarget?matricesEqual(manual,manualTarget):false;const suggested=manual&&!manualComplete?(()=>{try{return rref(manual).steps[0]?.operation.label}catch{return undefined}})():undefined;
 async function checkKind(){if(mode!=='system'||!prediction||!out.result||!('kind'in out.result))return;const ok=prediction===out.result.kind;setChecked(true);await Promise.all([recordAttempt({prefix:'rref',exerciseId:'linear.system.classification',module:'linear',finalState:ok?'correct':'incomplete',payload:{prediction,expected:out.result.kind,raw},skillIds:['linear.system.solve']}),recordSkillEvidence('linear.system.solve',ok?1:0,{independent:ok})]).catch(()=>undefined)}
 function applyManual(){if(!manual)return;try{const operation=opKind==='swap'?{kind:'swap' as const,rowA:rowA-1,rowB:rowB-1}:opKind==='scale'?{kind:'scale' as const,row:rowA-1,factor}:{kind:'replace' as const,targetRow:rowA-1,sourceRow:rowB-1,factor};const result=applyRowOperation(manual,operation);setManual(result.matrix);setManualHistory(history=>[...history,{operation:result.operation,matrix:result.matrix}]);setManualMessage(result.operation.label)}catch(error){setManualMessage(error instanceof Error?error.message:'That row operation could not be applied.')}}
 function undoManual(){const next=manualHistory.slice(0,-1);setManualHistory(next);try{setManual(next.at(-1)?.matrix??manualInitial(parse(raw),mode))}catch{}setManualMessage(undefined)}
 function autoComplete(){if(!manualTarget)return;setManual(manualTarget);setManualMessage('Auto-completed to RREF. Use this as a worked endpoint, not independent mastery evidence.')}
 function switchMode(next:Mode){setMode(next);setStep(0);setChecked(false);if(next==='inverse')setRaw('2 4\n0 -2');else if(next==='system')setRaw('1 1 3\n1 -1 1');else setRaw('1 2 3\n2 4 7')}
 return <section className="row-reduction-lab" data-testid="row-reduction-lab"><div className="row-reduction-lab__controls"><p className="section-label">Gauss–Jordan workspace</p><h2>Perform legal row operations—or inspect the engine's trace.</h2><div className="view-switch">{(['system','inverse','rref'] as Mode[]).map(value=><Button key={value} variant={mode===value?'primary':'secondary'} onClick={()=>switchMode(value)}>{value==='system'?'Solve system':value==='inverse'?'Find inverse':'RREF only'}</Button>)}</div><div className="logic-mode-tabs"><Button variant={workspace==='manual'?'primary':'secondary'} onClick={()=>setWorkspace('manual')}>Do the row operations</Button><Button variant={workspace==='guided'?'primary':'secondary'} onClick={()=>setWorkspace('guided')}>Inspect worked trace</Button></div><MatrixEditor label={mode==='system'?'Augmented matrix [A | b]':'Matrix'} value={raw} onChange={value=>{setRaw(value);setStep(0);setChecked(false)}}/>{mode==='system'&&<fieldset className="prediction-fieldset"><legend>Predict the solution type</legend>{(['unique','infinite','inconsistent'] as const).map(kind=><label key={kind}><input type="radio" checked={prediction===kind} onChange={()=>{setPrediction(kind);setChecked(false)}}/> {kind}</label>)}<Button disabled={!prediction||!out.result} onClick={()=>void checkKind()}>Check classification</Button>{checked&&out.result&&'kind'in out.result&&<Feedback tone={prediction===out.result.kind?'success':'error'}>{prediction===out.result.kind?'Correct.':`The RREF pattern indicates ${out.result.kind}.`}</Feedback>}</fieldset>}</div>
 <div className="row-reduction-lab__workspace">{out.error&&!out.M?<Feedback tone="error">{out.error}</Feedback>:workspace==='guided'?<><div className="step-toolbar"><Button variant="ghost" disabled={step===0} onClick={()=>setStep(value=>Math.max(0,value-1))}>← Previous</Button><span>Step {step} / {out.steps?.length??0}</span><Button variant="ghost" disabled={step>=(out.steps?.length??0)} onClick={()=>setStep(value=>Math.min(out.steps?.length??0,value+1))}>Next →</Button></div>{display&&<MatrixView value={display}/>}<div className="row-operation-explain">{step===0?<p>Start with the entered matrix. Advance to inspect each exact elementary row operation.</p>:<><strong>{out.steps?.[step-1]?.operation.label}</strong><p>Elementary row operations preserve the represented solution set.</p></>}</div></>:<><div className="math-panel__head"><div><p className="section-label">Manual operation workspace</p><h3>Choose the transformation yourself.</h3></div><Badge>{manualHistory.length} operations</Badge></div>{manual&&<MatrixView value={manual}/>}<div className="row-op-builder"><div className="row-op-builder__controls"><label>Operation<select value={opKind} onChange={e=>setOpKind(e.target.value as typeof opKind)}><option value="replace">Ri ← Ri + kRj</option><option value="scale">Ri ← kRi</option><option value="swap">Ri ↔ Rj</option></select></label><label>{opKind==='replace'?'Target row':'Row'}<input type="number" min="1" max={manual?.length??1} value={rowA} onChange={e=>setRowA(Number(e.target.value))}/></label>{opKind!=='scale'&&<label>{opKind==='replace'?'Source row':'Other row'}<input type="number" min="1" max={manual?.length??1} value={rowB} onChange={e=>setRowB(Number(e.target.value))}/></label>}{opKind!=='swap'&&<label>k<input value={factor} onChange={e=>setFactor(e.target.value)}/></label>}<Button variant="primary" onClick={applyManual}>Apply operation</Button></div>{manualMessage&&<Feedback tone={manualComplete?'success':'neutral'}>{manualMessage}</Feedback>}<div className="action-row"><Button variant="ghost" disabled={!manualHistory.length} onClick={undoManual}>Undo</Button><Button variant="ghost" disabled={!suggested} onClick={()=>setManualMessage(suggested?`Suggested next engine step: ${suggested}`:'Already reduced.')}>Suggest next</Button><Button variant="secondary" onClick={autoComplete}>Auto-complete</Button></div>{manualComplete&&<Feedback tone="success"><strong>Reduced.</strong> The manual matrix now matches exact RREF.</Feedback>}</div></>}{out.error&&<Feedback tone="error">{out.error}</Feedback>}{mode==='system'&&out.result&&'kind'in out.result&&<div className="formula-callout"><span>System classification</span><strong>{out.result.kind}</strong>{out.result.solution&&<small>Solution: ({out.result.solution.map(value=>value.toString()).join(', ')})</small>}</div>}{mode==='inverse'&&out.final&&<div><p className="section-label">Inverse extracted from [I | A⁻¹]</p><MatrixView value={out.final}/></div>}</div>
 <aside className="row-reduction-lab__rail"><p className="section-label">{workspace==='guided'?'Operation rail':'Your operations'}</p><ol className="step-list">{(workspace==='guided'?out.steps:manualHistory)?.map((item:any,index:number)=><li key={index} data-current={workspace==='guided'&&step===index+1}><button onClick={()=>workspace==='guided'&&setStep(index+1)}><span>{index+1}</span><strong>{workspace==='guided'?item.operation.label:item.operation.label}</strong></button></li>)}</ol></aside></section>
}
