import { useEffect, useMemo, useRef, useState } from 'react';
import { Brackets, CheckCircle2, CornerDownLeft, Lightbulb, Plus, RefreshCw, RotateCcw, ShieldCheck } from 'lucide-react';
import { PROOF_RULES, addScopedProofLine, closeProofScope, createScopedProof, openProofAssumption, scopedProofAvailableReferences, scopedProofComplete, type ProofMethod, type ProofRuleId, type ScopedProofState } from '@amat19/domain-logic';
import { Button } from '../../ui/Button';
import { Badge } from '../../ui/Badge';
import { Feedback } from '../../ui/Feedback';
import { createAttemptId, recordAssessmentResult } from '../../../lib/local-progress';
import { parsePositiveIntegerList } from '../../../lib/integer-input';

type Problem={id:string;method:ProofMethod;premises:string[];goal:string;title:string;description:string;hints:string[];skillId:string;defaultRule:ProofRuleId};
const PROBLEM_SETS:Record<ProofMethod,Problem[]>={
 direct:[
  {id:'direct-mt-conjunction',method:'direct',premises:['A -> B','~B','C'],goal:'~A & C',title:'Direct proof · MT + conjunction',description:'Derive the goal only from premises and earlier valid lines.',hints:['A → B and ∼B fit Modus Tollens.','Use MT to derive ∼A.','Combine ∼A with C using Conjunction.'],skillId:'logic.proof.direct',defaultRule:'MT'},
  {id:'direct-mp-conjunction',method:'direct',premises:['P -> Q','P','R'],goal:'Q & R',title:'Direct proof · MP + conjunction',description:'Use the supplied premises to derive both conjuncts before combining them.',hints:['P → Q and P fit Modus Ponens.','Use MP to derive Q.','Combine Q with R using Conjunction (CJ).'],skillId:'logic.proof.direct',defaultRule:'MP'}
 ],
 conditional:[
  {id:'conditional-chain-pqr',method:'conditional',premises:['P -> Q','Q -> R'],goal:'P -> R',title:'Conditional Proof · P to R',description:'Assume the antecedent, derive the consequent inside the subproof, then discharge the assumption.',hints:['Open the CP subproof by assuming P.','Use MP with P → Q and the assumption P.','Use MP again with Q → R, then close the scope.'],skillId:'logic.proof.conditional',defaultRule:'MP'},
  {id:'conditional-chain-abc',method:'conditional',premises:['A -> B','B -> C'],goal:'A -> C',title:'Conditional Proof · A to C',description:'Prove the implication through a fresh conditional subproof.',hints:['Open the CP subproof by assuming A.','Use MP to obtain B.','Use MP again to obtain C, then close CP.'],skillId:'logic.proof.conditional',defaultRule:'MP'}
 ],
 indirect:[
  {id:'indirect-mt-pq',method:'indirect',premises:['P -> Q','~Q'],goal:'~P',title:'Indirect Proof · P/Q',description:'Assume the negation of the target, derive an explicit contradiction, then discharge the assumption.',hints:['The negation of ∼P is ∼∼P. Open the IP scope with that preliminary assumption.','Use DN to derive P, then MP to derive Q.','Conjoin Q with premise ∼Q to make Q ∧ ∼Q, then close IP.'],skillId:'logic.proof.indirect',defaultRule:'DN'},
  {id:'indirect-mt-ab',method:'indirect',premises:['A -> B','~B'],goal:'~A',title:'Indirect Proof · A/B',description:'Use an indirect subproof on a structurally similar but distinct proposition set.',hints:['Open IP by assuming ∼∼A.','Use DN to derive A, then MP to derive B.','Combine B with ∼B as a contradiction, then close IP.'],skillId:'logic.proof.indirect',defaultRule:'DN'}
 ]
};
const selectableRules=PROOF_RULES.filter(rule=>rule.family!=='method'&&rule.id!=='Premise');

export default function FormalProofLab(){
 const[hydrated,setHydrated]=useState(false);const[method,setMethod]=useState<ProofMethod>('direct');const[problemIndex,setProblemIndex]=useState(0);const initial=PROBLEM_SETS.direct[0]!;const[state,setState]=useState<ScopedProofState>(()=>createScopedProof('direct',initial.premises,initial.goal));const[expression,setExpression]=useState('');const[ruleId,setRuleId]=useState<ProofRuleId>(initial.defaultRule);const[references,setReferences]=useState('1, 2');const[feedback,setFeedback]=useState<string>();const[hintLevel,setHintLevel]=useState(0);const recordedRef=useRef(false),invalidAttemptsRef=useRef(0),attemptIdRef=useRef(createAttemptId('formal-proof')),startedAtRef=useRef(new Date().toISOString());
 const problem=PROBLEM_SETS[method][problemIndex%PROBLEM_SETS[method].length]!;const complete=useMemo(()=>scopedProofComplete(state),[state]);const available=useMemo(()=>scopedProofAvailableReferences(state),[state]);const currentScope=state.currentScopeId!=='root';const problemFingerprint=`formal-proof::${problem.id}`;
 function resetTracking(){recordedRef.current=false;invalidAttemptsRef.current=0;attemptIdRef.current=createAttemptId('formal-proof');startedAtRef.current=new Date().toISOString()}
 function loadProblem(nextMethod:ProofMethod,index:number){const pool=PROBLEM_SETS[nextMethod],normalized=((index%pool.length)+pool.length)%pool.length,p=pool[normalized]!;setMethod(nextMethod);setProblemIndex(normalized);setState(createScopedProof(nextMethod,p.premises,p.goal));setExpression('');setRuleId(p.defaultRule);setReferences('');setFeedback(undefined);setHintLevel(0);resetTracking()}
 useEffect(()=>setHydrated(true),[]);
 useEffect(()=>{if(!complete||recordedRef.current)return;recordedRef.current=true;void recordAssessmentResult({prefix:'formal-proof',attemptId:attemptIdRef.current,startedAt:startedAtRef.current,exerciseId:`${problem.skillId}.guided`,problemFingerprint,module:'logic',skillId:problem.skillId,result:'correct',firstAttemptCorrect:invalidAttemptsRef.current===0&&hintLevel===0,incorrectAttempts:invalidAttemptsRef.current,hintsUsed:hintLevel,revealsUsed:0,difficulty:method==='direct'?'standard':'challenge',payload:{problemId:problem.id,method,lines:state.lines,hintsUsed:hintLevel,invalidSubmissions:invalidAttemptsRef.current}}).catch(()=>undefined)},[complete,hintLevel,method,problem.id,problem.skillId,problemFingerprint,state.lines]);
 function switchMethod(next:ProofMethod){loadProblem(next,0)}
 function nextProblem(){loadProblem(method,problemIndex+1)}
 function refs(){const parsed=parsePositiveIntegerList(references);if(parsed.status==='invalid')throw new RangeError(parsed.message);return parsed.value}
 function addLine(){if(!expression.trim())return;try{const next=addScopedProofLine(state,{expression,ruleId,references:refs()});const line=next.lines.at(-1)!;setState(next);setFeedback(line.message);if(line.ok)setExpression('');else invalidAttemptsRef.current+=1}catch(error){invalidAttemptsRef.current+=1;setFeedback(error instanceof Error?error.message:'That proof line could not be added.')}}
 function openScope(){try{const next=openProofAssumption(state);setState(next);setFeedback(next.lines.at(-1)!.message);setReferences('');setRuleId(method==='indirect'?'DN':'MP')}catch(error){invalidAttemptsRef.current+=1;setFeedback(error instanceof Error?error.message:'The subproof could not be opened.')}}
 function closeScope(){try{const next=closeProofScope(state);setState(next);setFeedback(next.lines.at(-1)!.message)}catch(error){invalidAttemptsRef.current+=1;setFeedback(error instanceof Error?error.message:'The subproof is not ready to close.')}}
 function reset(){loadProblem(method,problemIndex)}
 return <section className="proof-lab" data-testid="formal-proof-lab" data-hydrated={hydrated?'true':undefined} data-problem-id={problem.id}>
  <header className="proof-lab__goal"><div><p className="section-label">Scoped formal proof workspace</p><h2>Derive the goal one justified line at a time.</h2><p>{problem.description}</p><div className="logic-mode-tabs">{(['direct','conditional','indirect'] as ProofMethod[]).map(value=><Button key={value} variant={method===value?'primary':'secondary'} onClick={()=>switchMethod(value)}>{value==='direct'?<ShieldCheck size={15}/>:<Brackets size={15}/>} {value[0]!.toUpperCase()+value.slice(1)}</Button>)}</div></div><div className="goal-card"><span>Goal</span><strong>{problem.goal}</strong><Badge>{currentScope?'subproof open':'root scope'}</Badge><small>{problem.title}</small></div></header>
  <div className="action-row"><Button variant="secondary" type="button" onClick={nextProblem}><RefreshCw size={16}/> New {method} problem</Button><span className="section-context">Distinct problem {problemIndex+1}/{PROBLEM_SETS[method].length} · fingerprint {problem.id}</span></div>
  <div className="proof-table-wrap" role="region" aria-label="Proof lines" tabIndex={0}><table className="proof-table"><caption className="sr-only">Scoped formal proof lines.</caption><thead><tr><th>#</th><th>Statement</th><th>Justification</th><th>Scope / status</th></tr></thead><tbody>{state.lines.map(line=><tr key={line.lineNumber} data-valid={line.ok}><th>{line.lineNumber}</th><td className="logic-expression"><span style={{display:'inline-block',paddingInlineStart:`${line.scopeDepth*1.35}rem`}}>{line.scopeDepth>0?'│ ':''}{line.expression}</span></td><td>{line.ruleId}{line.references.length?` · ${line.references.join(', ')}`:''}</td><td><span className="proof-status" data-valid={line.ok}>{line.ok?line.role==='assumption'?'Assumption':line.role==='closure'?'Scope discharged':'Valid':'Needs revision'}</span>{!line.ok&&<small>{line.message}</small>}</td></tr>)}</tbody></table></div>
  {complete&&<Feedback tone="success"><CheckCircle2 size={18}/><strong>QED.</strong> The final valid root-scope line matches the goal. {invalidAttemptsRef.current>0||hintLevel>0?'This completion is recorded as assisted evidence.':'This completion is eligible for independent evidence unless this exact problem was already mastered independently.'}</Feedback>}
  {method!=='direct'&&!currentScope&&!complete&&<div className="math-panel"><p className="section-label">Proof method</p><p>{method==='conditional'?'Conditional Proof begins by assuming the antecedent of the target implication.':'Indirect Proof begins by assuming the negation of the target.'}</p><Button variant="primary" onClick={openScope}><CornerDownLeft size={16}/> Open preliminary assumption</Button></div>}
  <form className="proof-editor" onSubmit={event=>{event.preventDefault();addLine()}}><div className="proof-editor__statement"><label className="form-field"><span className="form-field__label">Next proof statement</span><input className="text-input logic-input" value={expression} onChange={event=>setExpression(event.target.value)} placeholder={method==='indirect'?'e.g. ~~P or P':'e.g. Q'}/><span className="form-field__hint">Aliases: ~ / ¬, & / ∧, | / ∨, -&gt; / →, &lt;-&gt; / ↔</span></label></div><label className="form-field"><span className="form-field__label">Proof rule</span><select className="select-input" value={ruleId} onChange={event=>setRuleId(event.target.value as ProofRuleId)}>{selectableRules.map(rule=><option key={rule.id} value={rule.id}>{rule.id} · {rule.name}</option>)}</select></label><label className="form-field"><span className="form-field__label">Cited line numbers</span><input className="text-input" value={references} onChange={event=>setReferences(event.target.value)} placeholder={available.slice(-2).join(', ')}/><span className="form-field__hint">Available here: {available.length?available.join(', '):'none'}</span></label><div className="action-row proof-editor__actions"><Button variant="primary" type="submit" disabled={!expression.trim()||complete}><Plus size={16}/> Add checked line</Button>{currentScope&&<Button variant="secondary" type="button" onClick={closeScope}><CornerDownLeft size={16}/> Close {method==='conditional'?'CP':'IP'} scope</Button>}<Button variant="ghost" type="button" onClick={reset}><RotateCcw size={16}/> Reset attempt</Button></div></form>
  {feedback&&<Feedback tone={state.lines.at(-1)?.ok?'neutral':'error'}>{feedback}</Feedback>}
  <div className="proof-hints"><div className="action-row"><Button variant="ghost" disabled={hintLevel>=problem.hints.length} onClick={()=>setHintLevel(level=>Math.min(problem.hints.length,level+1))}><Lightbulb size={16}/> Reveal {hintLevel?'next ':''}hint</Button>{hintLevel>0&&<span>{hintLevel}/{problem.hints.length} hints revealed</span>}</div>{hintLevel>0&&<ol>{problem.hints.slice(0,hintLevel).map(hint=><li key={hint}>{hint}</li>)}</ol>}</div>
  <aside className="proof-reference"><p className="section-label">Rule reference</p><div className="rule-grid">{PROOF_RULES.filter(rule=>rule.family!=='method').map(rule=><details key={rule.id}><summary><strong>{rule.id}</strong> · {rule.name}</summary><p>{rule.description}</p></details>)}</div></aside>
 </section>
}
