import { useEffect, useMemo, useState } from 'react';
import { annuityPaymentForValue, annuityValue, type AnnuityTiming, type ValueDirection } from '@amat19/domain-finance';
import { Button } from '../../ui/Button'; import { Feedback } from '../../ui/Feedback';
import { loadDraft, saveDraft } from '../../../lib/draft'; import { recordAttempt, recordSkillEvidence } from '../../../lib/local-progress';
const LAB_ID='finance.annuity',CONTENT_VERSION='1';
type Draft={payment:number;rate:number;n:number;timing:AnnuityTiming;direction:ValueDirection;solveFor:'value'|'payment';target:number};
const money=(v:number)=>new Intl.NumberFormat('en-PH',{minimumFractionDigits:2,maximumFractionDigits:4}).format(v);
export default function AnnuityLab(){const[payment,setPayment]=useState(1500),[rate,setRate]=useState(.01),[n,setN]=useState(12),[timing,setTiming]=useState<AnnuityTiming>('immediate'),[direction,setDirection]=useState<ValueDirection>('present'),[solveFor,setSolveFor]=useState<'value'|'payment'>('value'),[target,setTarget]=useState(20000),[prediction,setPrediction]=useState<AnnuityTiming>(),[checked,setChecked]=useState(false),[restored,setRestored]=useState(false);
 useEffect(()=>{loadDraft<Draft>(LAB_ID,CONTENT_VERSION).then(d=>{if(d){setPayment(d.payment);setRate(d.rate);setN(d.n);setTiming(d.timing);setDirection(d.direction);setSolveFor(d.solveFor);setTarget(d.target);}setRestored(true);});},[]);useEffect(()=>{if(!restored)return;const t=setTimeout(()=>void saveDraft(LAB_ID,CONTENT_VERSION,{payment,rate,n,timing,direction,solveFor,target}),250);return()=>clearTimeout(t);},[restored,payment,rate,n,timing,direction,solveFor,target]);
 const result=useMemo(()=>{try{return{value:solveFor==='value'?annuityValue(payment,rate,n,timing,direction):annuityPaymentForValue(target,rate,n,timing,direction),error:undefined}}catch(e){return{value:undefined,error:e instanceof Error?e.message:'Could not value the annuity.'}}},[payment,rate,n,timing,direction,solveFor,target]);
 async function checkTiming(){if(!prediction)return;const ok=prediction===timing;setChecked(true);await Promise.all([recordAttempt({prefix:'annuity',exerciseId:'finance.annuity.timing',module:'finance',finalState:ok?'correct':'incomplete',payload:{timing,prediction}}),recordSkillEvidence('finance.annuity',ok?1:0)]).catch(()=>undefined);}
 return <section className="finance-lab" data-testid="annuity-lab"><div className="finance-lab__controls"><p className="section-label">Level-payment annuities</p><h2>Place the payments first; then choose the factor.</h2><div className="two-column-fields"><label className="form-field"><span className="form-field__label">Rate per payment period i</span><input className="text-input" type="number" step="0.001" value={rate} onChange={e=>setRate(Number(e.target.value))}/></label><label className="form-field"><span className="form-field__label">Number of payments n</span><input className="text-input" type="number" min="0" step="1" value={n} onChange={e=>setN(Number(e.target.value))}/></label></div><div className="view-switch"><Button variant={timing==='immediate'?'primary':'secondary'} onClick={()=>{setTiming('immediate');setChecked(false)}}>Immediate · end of period</Button><Button variant={timing==='due'?'primary':'secondary'} onClick={()=>{setTiming('due');setChecked(false)}}>Due · beginning of period</Button></div><div className="view-switch"><Button variant={direction==='present'?'primary':'secondary'} onClick={()=>setDirection('present')}>Present value</Button><Button variant={direction==='future'?'primary':'secondary'} onClick={()=>setDirection('future')}>Future value</Button></div><div className="view-switch"><Button variant={solveFor==='value'?'primary':'secondary'} onClick={()=>setSolveFor('value')}>Solve value</Button><Button variant={solveFor==='payment'?'primary':'secondary'} onClick={()=>setSolveFor('payment')}>Solve payment</Button></div>{solveFor==='value'?<label className="form-field"><span className="form-field__label">Level payment R</span><input className="text-input" type="number" value={payment} onChange={e=>setPayment(Number(e.target.value))}/></label>:<label className="form-field"><span className="form-field__label">Target {direction} value</span><input className="text-input" type="number" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label>}
 <fieldset className="prediction-fieldset"><legend>Predict payment timing</legend><label><input type="radio" checked={prediction==='immediate'} onChange={()=>{setPrediction('immediate');setChecked(false)}}/> First payment is one period after the valuation date</label><label><input type="radio" checked={prediction==='due'} onChange={()=>{setPrediction('due');setChecked(false)}}/> First payment is at the beginning of the first period</label><Button disabled={!prediction} onClick={checkTiming}>Check timing</Button>{checked&&<Feedback tone={prediction===timing?'success':'error'}>{prediction===timing?'Correct.':'Inspect where the first payment sits on the timeline.'}</Feedback>}</fieldset></div>
 <div className="finance-lab__visual"><p className="section-label">Payment timeline</p><AnnuityTimeline n={n} timing={timing} direction={direction}/>{result.error?<Feedback tone="error">{result.error}</Feedback>:<div className="formula-callout finance-result"><span>{solveFor==='value'?`${direction==='present'?'Present':'Future'} value`:'Required level payment'}</span><strong>PHP {money(result.value!.value)}</strong></div>}</div><aside className="finance-lab__trace"><p className="section-label">Solution trace</p>{result.value?.trace.map(s=><article className="trace-step" key={s.id}><strong>{s.label}</strong><code>{s.expression}</code><p>{s.explanation}</p></article>)}</aside></section>}
function AnnuityTimeline({n,timing,direction}:{n:number;timing:AnnuityTiming;direction:ValueDirection}){const count=Math.max(1,Math.min(n,10));return <figure className="finance-timeline"><svg viewBox="0 0 600 190" role="img" aria-label={`${timing} annuity payment timeline`}><line x1="45" y1="95" x2="555" y2="95"/>{Array.from({length:count+1},(_,i)=>{const x=55+490*i/count;const has=timing==='due'?i<count:i>0;return <g key={i}><line x1={x} y1="87" x2={x} y2="103"/><text x={x} y="125" textAnchor="middle">{i}</text>{has&&<><circle cx={x} cy="70" r="7"/><text x={x} y="48" textAnchor="middle">R</text></>}</g>})}<text x={direction==='present'?55:545} y="165" textAnchor={direction==='present'?'start':'end'}>focal date for {direction} value</text></svg><figcaption>{timing==='due'?'Payments occur at the beginning of each period.':'Payments occur at the end of each period.'} {n>10?'The diagram compresses the middle payments.':''}</figcaption></figure>}
