import { useEffect, useMemo, useRef, useState } from 'react';
import { annuityPaymentForValue, annuityValue, type AnnuityTiming, type ValueDirection } from '@amat19/domain-finance';
import { Button } from '../../ui/Button';
import StepTrace from '../../math/StepTrace'; import { Feedback } from '../../ui/Feedback';
import { loadDraft, saveDraft } from '../../../lib/draft'; import { createAttemptId, recordAssessmentResult } from '../../../lib/local-progress';
import { usePersistenceFlush } from '../../../lib/use-persistence-flush';
import { financeCertaintyLabel } from '../../../lib/finance-display';
const LAB_ID='finance.annuity',CONTENT_VERSION='1';
type Draft={payment:string|number;rate:string|number;n:string|number;timing:AnnuityTiming;direction:ValueDirection;solveFor:'value'|'payment';target:string|number};
const textOf=(value:string|number)=>String(value);
const money=(v:number)=>new Intl.NumberFormat('en-PH',{minimumFractionDigits:2,maximumFractionDigits:4}).format(v);
export default function AnnuityLab(){const[payment,setPayment]=useState('1500'),[rate,setRate]=useState('0.01'),[n,setN]=useState('12'),[timing,setTiming]=useState<AnnuityTiming>('immediate'),[direction,setDirection]=useState<ValueDirection>('present'),[solveFor,setSolveFor]=useState<'value'|'payment'>('value'),[target,setTarget]=useState('20000'),[prediction,setPrediction]=useState<AnnuityTiming>(),[checked,setChecked]=useState(false),[restored,setRestored]=useState(false);const userInteracted=useRef(false);const incorrectAttemptsRef=useRef(0),attemptIdRef=useRef(createAttemptId('annuity-timing')),startedAtRef=useRef(new Date().toISOString());
 useEffect(()=>{loadDraft<Draft>(LAB_ID,CONTENT_VERSION).then(d=>{if(!userInteracted.current&&d){setPayment(textOf(d.payment));setRate(textOf(d.rate));setN(textOf(d.n));setTiming(d.timing);setDirection(d.direction);setSolveFor(d.solveFor);setTarget(textOf(d.target));}setRestored(true);});},[]);useEffect(()=>{if(!restored)return;const t=setTimeout(()=>void saveDraft(LAB_ID,CONTENT_VERSION,{payment,rate,n,timing,direction,solveFor,target}),250);return()=>clearTimeout(t);},[restored,payment,rate,n,timing,direction,solveFor,target]);
 usePersistenceFlush(()=>saveDraft(LAB_ID,CONTENT_VERSION,{payment,rate,n,timing,direction,solveFor,target}),restored);
 const result=useMemo(()=>{try{return{value:solveFor==='value'?annuityValue(payment,rate,n,timing,direction):annuityPaymentForValue(target,rate,n,timing,direction),error:undefined}}catch(e){return{value:undefined,error:e instanceof Error?e.message:'Could not value the annuity.'}}},[payment,rate,n,timing,direction,solveFor,target]);
 const timingFingerprint=`annuity-timing::${timing}`;useEffect(()=>{incorrectAttemptsRef.current=0;attemptIdRef.current=createAttemptId('annuity-timing');startedAtRef.current=new Date().toISOString()},[timingFingerprint]);
 async function checkTiming(){if(!prediction)return;const ok=prediction===timing,wrongBefore=incorrectAttemptsRef.current;if(!ok)incorrectAttemptsRef.current+=1;setChecked(true);await recordAssessmentResult({prefix:'annuity',attemptId:attemptIdRef.current,startedAt:startedAtRef.current,exerciseId:'finance.annuity.timing',problemFingerprint:timingFingerprint,module:'finance',skillId:timing==='immediate'?'finance.annuity.immediate':'finance.annuity.due',result:ok?'correct':'incorrect',firstAttemptCorrect:ok&&wrongBefore===0,incorrectAttempts:incorrectAttemptsRef.current,hintsUsed:0,revealsUsed:0,difficulty:'intro',payload:{timing,prediction}}).catch(()=>undefined);}
 return <section className="finance-lab" data-testid="annuity-lab" data-hydrated={restored?'true':undefined} onPointerDown={()=>{userInteracted.current=true}} onKeyDown={event=>{if(event.target instanceof HTMLElement&&event.target.closest('button,input,select,textarea'))userInteracted.current=true}}><div className="finance-lab__controls"><h2>Place the payments first; then choose the factor.</h2><p className="section-context">Level-payment annuities</p><div className="two-column-fields"><label className="form-field"><span className="form-field__label">Rate per payment period i</span><input className="text-input" type="number" step="0.001" value={rate} onChange={e=>setRate(e.target.value)}/></label><label className="form-field"><span className="form-field__label">Number of payments n</span><input className="text-input" type="number" min="0" step="1" value={n} onChange={e=>setN(e.target.value)}/></label></div><div className="view-switch"><Button variant={timing==='immediate'?'primary':'secondary'} onClick={()=>{setTiming('immediate');setChecked(false)}}>Immediate · end of period</Button><Button variant={timing==='due'?'primary':'secondary'} onClick={()=>{setTiming('due');setChecked(false)}}>Due · beginning of period</Button></div><div className="view-switch"><Button variant={direction==='present'?'primary':'secondary'} onClick={()=>setDirection('present')}>Present value</Button><Button variant={direction==='future'?'primary':'secondary'} onClick={()=>setDirection('future')}>Future value</Button></div><div className="view-switch"><Button variant={solveFor==='value'?'primary':'secondary'} onClick={()=>setSolveFor('value')}>Solve value</Button><Button variant={solveFor==='payment'?'primary':'secondary'} onClick={()=>setSolveFor('payment')}>Solve payment</Button></div>{solveFor==='value'?<label className="form-field"><span className="form-field__label">Level payment R</span><input className="text-input" type="number" value={payment} onChange={e=>setPayment(e.target.value)}/></label>:<label className="form-field"><span className="form-field__label">Target {direction} value</span><input className="text-input" type="number" value={target} onChange={e=>setTarget(e.target.value)}/></label>}
 <fieldset className="prediction-fieldset"><legend>Predict payment timing</legend><label><input type="radio" checked={prediction==='immediate'} onChange={()=>{setPrediction('immediate');setChecked(false)}}/> First payment is one period after the valuation date</label><label><input type="radio" checked={prediction==='due'} onChange={()=>{setPrediction('due');setChecked(false)}}/> First payment is at the beginning of the first period</label><Button disabled={!prediction} onClick={checkTiming}>Check timing</Button>{checked&&<Feedback tone={prediction===timing?'success':'error'}>{prediction===timing?'Correct.':'Inspect where the first payment sits on the timeline.'}</Feedback>}</fieldset></div>
 <div className="finance-lab__visual"><p className="section-label">Payment timeline</p>{result.value?<AnnuityTimeline n={Number(n)} timing={timing} direction={direction}/>:<p className="experimental-note">Enter a valid annuity to render its payment timeline.</p>}{result.error?<Feedback tone="error">{result.error}</Feedback>:<div className="formula-callout finance-result"><span>{solveFor==='value'?`${direction==='present'?'Present':'Future'} value`:'Required level payment'}</span><strong>PHP {money(result.value!.value)}</strong><small>{financeCertaintyLabel(result.value!)}</small></div>}</div><aside className="finance-lab__trace"><p className="section-label">Solution trace</p>{result.value&&<StepTrace steps={result.value.trace} initialCount={4}/>}</aside></section>}
function AnnuityTimeline({n,timing,direction}:{n:number;timing:AnnuityTiming;direction:ValueDirection}){
 const total=Number.isInteger(n)&&n>=0?n:0;const visible=Math.min(total,10),divisions=Math.max(1,visible);
 return <figure className="finance-timeline" data-payment-count={total}><svg viewBox="0 0 600 190" role="img" aria-label={`${timing} annuity payment timeline with ${total} payment${total===1?'':'s'}`}><line x1="45" y1="95" x2="555" y2="95"/>{Array.from({length:visible+1},(_,i)=>{const x=55+490*i/divisions;const has=total>0&&(timing==='due'?i<visible:i>0);return <g key={i}><line x1={x} y1="87" x2={x} y2="103"/><text x={x} y="125" textAnchor="middle">{i}</text>{has&&<><circle cx={x} cy="70" r="7"/><text x={x} y="48" textAnchor="middle">R</text></>}</g>})}<text x={direction==='present'?55:545} y="165" textAnchor={direction==='present'?'start':'end'}>focal date for {direction} value</text></svg><figcaption>{total===0?'No payments: the annuity factor and value are both 0.':timing==='due'?'Payments occur at the beginning of each period.':'Payments occur at the end of each period.'} {total>10?'The diagram compresses the middle payments.':''}</figcaption></figure>
}
