import { useEffect, useMemo, useState } from 'react';
import { compoundAccumulation, effectiveToNominal, nominalAccumulation, nominalToEffective, roundFinance, simpleAccumulation, valueAtTime } from '@amat19/domain-finance';
import { Button } from '../../ui/Button';
import { Feedback } from '../../ui/Feedback';
import { loadDraft, saveDraft } from '../../../lib/draft';
import { recordAttempt, recordSkillEvidence } from '../../../lib/local-progress';
type Mode='simple'|'compound'|'nominal'|'tvm';
const LAB_ID='finance.interest'; const CONTENT_VERSION='1';
type Draft={mode:Mode;principal:number;rate:number;years:number;frequency:number;futureAmount:number;fromTime:number;toTime:number};
const money=(v:number)=>new Intl.NumberFormat('en-PH',{minimumFractionDigits:2,maximumFractionDigits:4}).format(v);
const pct=(v:number)=>`${(v*100).toFixed(4).replace(/0+$/,'').replace(/\.$/,'')}%`;
export default function InterestLab(){
 const[mode,setMode]=useState<Mode>('compound'),[principal,setPrincipal]=useState(10000),[rate,setRate]=useState(.05),[years,setYears]=useState(3),[frequency,setFrequency]=useState(4),[futureAmount,setFutureAmount]=useState(25000),[fromTime,setFromTime]=useState(0),[toTime,setToTime]=useState(6),[restored,setRestored]=useState(false),[prediction,setPrediction]=useState<'simple'|'compound'>(),[checked,setChecked]=useState(false);
 useEffect(()=>{loadDraft<Draft>(LAB_ID,CONTENT_VERSION).then(d=>{if(d){setMode(d.mode);setPrincipal(d.principal);setRate(d.rate);setYears(d.years);setFrequency(d.frequency);setFutureAmount(d.futureAmount);setFromTime(d.fromTime);setToTime(d.toTime);}setRestored(true);});},[]);
 useEffect(()=>{if(!restored)return;const t=window.setTimeout(()=>void saveDraft(LAB_ID,CONTENT_VERSION,{mode,principal,rate,years,frequency,futureAmount,fromTime,toTime}),250);return()=>clearTimeout(t);},[restored,mode,principal,rate,years,frequency,futureAmount,fromTime,toTime]);
 const result=useMemo(()=>{try{if(mode==='simple')return{main:simpleAccumulation(principal,rate,years),label:'Accumulated value',secondary:`Interest earned = ${money(simpleAccumulation(principal,rate,years).value-principal)}`};if(mode==='compound')return{main:compoundAccumulation(principal,rate,years),label:'Accumulated value',secondary:`Interest earned = ${money(compoundAccumulation(principal,rate,years).value-principal)}`};if(mode==='nominal'){const main=nominalAccumulation(principal,rate,frequency,years),eff=nominalToEffective(rate,frequency);return{main,label:'Accumulated value',secondary:`Equivalent annual effective rate = ${pct(eff.value)}`};}const pv=valueAtTime(futureAmount,toTime,fromTime,rate);return{main:pv,label:`Equivalent value at t = ${fromTime}`,secondary:`Move PHP ${money(futureAmount)} from t=${toTime} to t=${fromTime}`};}catch(e){return{error:e instanceof Error?e.message:'The financial model could not be evaluated.'};}},[mode,principal,rate,years,frequency,futureAmount,fromTime,toTime]);
 const effective=useMemo(()=>{try{return mode==='nominal'?nominalToEffective(rate,frequency).value:undefined}catch{return undefined}},[mode,rate,frequency]);
 async function checkModel(){if(!prediction)return;const expected=mode==='simple'?'simple':'compound';const ok=prediction===expected;setChecked(true);await Promise.all([recordAttempt({prefix:'finance',exerciseId:'finance.interest.model',module:'finance',finalState:ok?'correct':'incomplete',payload:{mode,prediction,expected}}),recordSkillEvidence('finance.interest',ok?1:0)]).catch(()=>undefined);}
 return <section className="finance-lab" data-testid="interest-lab">
  <div className="finance-lab__controls">
   <p className="section-label">Interest & time value</p><h2>Move money through time with the right accumulation rule.</h2>
   <div className="view-switch" role="tablist" aria-label="Interest model">{(['simple','compound','nominal','tvm'] as Mode[]).map(m=><Button key={m} variant={mode===m?'primary':'secondary'} role="tab" aria-selected={mode===m} onClick={()=>{setMode(m);setChecked(false)}}>{m==='tvm'?'Time value':m[0]!.toUpperCase()+m.slice(1)}</Button>)}</div>
   {mode!=='tvm'&&<><div className="number-pair"><label className="form-field"><span className="form-field__label">Principal P</span><input className="text-input" type="number" min="0" step="100" value={principal} onChange={e=>setPrincipal(Number(e.target.value))}/></label><label className="form-field"><span className="form-field__label">Annual rate</span><input className="text-input" type="number" step="0.001" value={rate} onChange={e=>setRate(Number(e.target.value))}/><span className="form-field__hint">Use decimal form: 0.05 = 5%</span></label></div><div className="number-pair"><label className="form-field"><span className="form-field__label">Years t</span><input className="text-input" type="number" min="0" step="0.25" value={years} onChange={e=>setYears(Number(e.target.value))}/></label>{mode==='nominal'&&<label className="form-field"><span className="form-field__label">Conversions per year m</span><input className="text-input" type="number" min="1" step="1" value={frequency} onChange={e=>setFrequency(Number(e.target.value))}/></label>}</div></>}
   {mode==='tvm'&&<><label className="form-field"><span className="form-field__label">Cash amount</span><input className="text-input" type="number" value={futureAmount} onChange={e=>setFutureAmount(Number(e.target.value))}/></label><div className="number-triple"><label className="form-field"><span className="form-field__label">From time</span><input className="text-input" type="number" value={toTime} onChange={e=>setToTime(Number(e.target.value))}/></label><label className="form-field"><span className="form-field__label">To focal time</span><input className="text-input" type="number" value={fromTime} onChange={e=>setFromTime(Number(e.target.value))}/></label><label className="form-field"><span className="form-field__label">Effective rate per period</span><input className="text-input" type="number" step="0.001" value={rate} onChange={e=>setRate(Number(e.target.value))}/></label></div></>}
   {(mode==='simple'||mode==='compound')&&<fieldset className="prediction-fieldset"><legend>Before calculating: which model is active?</legend><label><input type="radio" name="finance-model" checked={prediction==='simple'} onChange={()=>{setPrediction('simple');setChecked(false)}}/> Simple interest — interest only on original principal</label><label><input type="radio" name="finance-model" checked={prediction==='compound'} onChange={()=>{setPrediction('compound');setChecked(false)}}/> Compound interest — interest on accumulated balance</label><Button type="button" variant="secondary" disabled={!prediction} onClick={checkModel}>Check model</Button>{checked&&<Feedback tone={prediction===mode?'success':'error'}>{prediction===mode?'Correct model.':'Look at whether previously earned interest itself earns interest.'}</Feedback>}</fieldset>}
  </div>
  <div className="finance-lab__visual">
   <p className="section-label">Synchronized timeline</p><FinanceTimeline mode={mode} principal={principal} resultValue={result.main?.value} years={years} fromTime={fromTime} toTime={toTime} amount={futureAmount}/>
   {result.error?<Feedback tone="error" role="alert">{result.error}</Feedback>:<><div className="formula-callout finance-result"><span>{result.label}</span><strong>PHP {money(result.main!.value)}</strong><small>{result.secondary}</small></div>{mode==='nominal'&&effective!==undefined&&<div className="formula-callout"><span>Rate equivalence</span><strong>j({frequency}) = {pct(rate)} ↔ i = {pct(effective)}</strong><small>Equivalent rates produce the same one-year accumulation.</small></div>}</>}
  </div>
  <aside className="finance-lab__trace"><p className="section-label">Why each step is legal</p>{result.main?.trace.map(step=><article className="trace-step" key={step.id}><strong>{step.label}</strong><code>{step.expression}</code><p>{step.explanation}</p></article>)}</aside>
 </section>;
}
function FinanceTimeline({mode,principal,resultValue,years,fromTime,toTime,amount}:{mode:Mode;principal:number;resultValue?:number;years:number;fromTime:number;toTime:number;amount:number}){const start=mode==='tvm'?Math.min(fromTime,toTime):0,end=mode==='tvm'?Math.max(fromTime,toTime):years||1,span=Math.max(1,end-start);const x=(t:number)=>60+480*(t-start)/span;return <figure className="finance-timeline"><svg viewBox="0 0 600 180" role="img" aria-label="Financial timeline"><line x1="55" y1="90" x2="545" y2="90"/>{Array.from({length:Math.min(8,Math.ceil(span)+1)},(_,i)=>{const t=start+(span*i/Math.min(7,Math.ceil(span)));return <g key={i}><line x1={x(t)} y1="82" x2={x(t)} y2="98"/><text x={x(t)} y="118" textAnchor="middle">t={Number(t.toFixed(2))}</text></g>})}{mode==='tvm'?<><circle cx={x(toTime)} cy="90" r="8"/><text x={x(toTime)} y="55" textAnchor="middle">PHP {money(amount)}</text><circle cx={x(fromTime)} cy="90" r="8"/><text x={x(fromTime)} y="145" textAnchor="middle">PHP {resultValue===undefined?'—':money(resultValue)}</text></>:<><circle cx={x(0)} cy="90" r="8"/><text x={x(0)} y="55" textAnchor="middle">P = {money(principal)}</text><circle cx={x(years)} cy="90" r="8"/><text x={x(years)} y="145" textAnchor="middle">A = {resultValue===undefined?'—':money(resultValue)}</text></>}</svg><figcaption>Amounts may be compared or added only when they are valued at the same focal date.</figcaption></figure>}
