import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CheckCircle2, RotateCcw, WandSparkles, XCircle } from 'lucide-react';
import { checkEquivalence, checkEquivalenceRewrite, evaluateLogic, formatLogic, generateAssignments, parseLogic, PROOF_RULES, type EquivalenceRuleId } from '@amat19/domain-logic';
import { Button } from '../../ui/Button';
import { Badge } from '../../ui/Badge';
import { Feedback } from '../../ui/Feedback';
import { loadDraft, saveDraft } from '../../../lib/draft';
import { recordAttempt, recordSkillEvidence } from '../../../lib/local-progress';

const LAB_ID='logic.equivalence';const CONTENT_VERSION='3';
type Draft={left:string;right:string};type WorkspaceMode='compare'|'transform';
const PRESETS=[{label:'Contrapositive',left:'P -> Q',right:'~Q -> ~P'},{label:'Converse',left:'P -> Q',right:'Q -> P'},{label:'De Morgan',left:'~(P | Q)',right:'~P & ~Q'}];
const TRANSFORM_PRESETS=[{label:'De Morgan',start:'~(P & Q)',goal:'~P | ~Q'},{label:'Material implication',start:'P -> Q',goal:'~P | Q'},{label:'Double negation',start:'P',goal:'~~P'},{label:'Transposition',start:'P -> Q',goal:'~Q -> ~P'}];
const EQUIV_RULES=PROOF_RULES.filter(rule=>rule.family==='equivalence');

type TransformStep={expression:string;ruleId?:EquivalenceRuleId;message?:string};
export default function EquivalenceLab(){
 const[mode,setMode]=useState<WorkspaceMode>('compare');const[left,setLeft]=useState('P -> Q');const[right,setRight]=useState('~Q -> ~P');const[prediction,setPrediction]=useState<'equivalent'|'different'>();const[revealed,setRevealed]=useState(false);const[restored,setRestored]=useState(false);
 const[start,setStart]=useState('~(P & Q)');const[goal,setGoal]=useState('~P | ~Q');const[history,setHistory]=useState<TransformStep[]>([{expression:'~(P & Q)'}]);const[nextExpression,setNextExpression]=useState('~P | ~Q');const[rule,setRule]=useState<EquivalenceRuleId>('DM');const[transformFeedback,setTransformFeedback]=useState<{ok:boolean;message:string}>();
 useEffect(()=>{loadDraft<Draft>(LAB_ID,CONTENT_VERSION).then(draft=>{if(draft){setLeft(draft.left);setRight(draft.right)}setRestored(true)})},[]);
 useEffect(()=>{if(!restored)return;const timer=window.setTimeout(()=>void saveDraft(LAB_ID,CONTENT_VERSION,{left,right}),300);return()=>window.clearTimeout(timer)},[left,right,restored]);
 const analysis=useMemo(()=>{try{const result=checkEquivalence(left,right);const leftAst=parseLogic(left),rightAst=parseLogic(right);const assignments=generateAssignments(result.symbols);return{error:undefined,result,rows:assignments.map((assignment,index)=>({index,assignment,left:evaluateLogic(leftAst,assignment).value,right:evaluateLogic(rightAst,assignment).value})),normalizedLeft:formatLogic(leftAst),normalizedRight:formatLogic(rightAst)}}catch(error){return{error:error instanceof Error?error.message:'The pair could not be analyzed.'}}},[left,right]);
 const predictionCorrect=analysis.result?(prediction==='equivalent')===analysis.result.equivalent:false;
 async function reveal(){if(!prediction||!analysis.result)return;setRevealed(true);await Promise.all([recordAttempt({prefix:'equivalence',exerciseId:'logic.equivalence.compare',module:'logic',finalState:predictionCorrect?'correct':'incomplete',payload:{left,right,prediction,equivalent:analysis.result.equivalent},skillIds:['logic.equivalence.test']}),recordSkillEvidence('logic.equivalence.test',predictionCorrect?1:0,{independent:predictionCorrect})]).catch(()=>undefined)}
 function resetTransform(newStart=start,newGoal=goal){setHistory([{expression:newStart}]);setNextExpression(newGoal);setRule('DM');setTransformFeedback(undefined);setStart(newStart);setGoal(newGoal)}
 async function addTransform(){const current=history.at(-1)!.expression;try{const result=checkEquivalenceRewrite(current,nextExpression,rule);setTransformFeedback(result);if(!result.ok)return;const normalized=formatLogic(parseLogic(nextExpression));const next=[...history,{expression:normalized,ruleId:rule,message:result.message}];setHistory(next);setNextExpression('');const reached=checkEquivalence(normalized,goal).equivalent&&formatLogic(parseLogic(normalized))===formatLogic(parseLogic(goal));if(reached){await Promise.all([recordAttempt({prefix:'equivalence-transform',exerciseId:'logic.equivalence.transform',module:'logic',finalState:'correct',payload:{start,goal,steps:next},skillIds:['logic.equivalence.transform'],difficulty:'standard'}),recordSkillEvidence('logic.equivalence.transform',1,{independent:true})]).catch(()=>undefined)}}catch(error){setTransformFeedback({ok:false,message:error instanceof Error?error.message:'That rewrite could not be parsed.'})}}
 const transformReached=useMemo(()=>{try{return formatLogic(parseLogic(history.at(-1)!.expression))===formatLogic(parseLogic(goal))}catch{return false}},[history,goal]);
 return <section className="learning-lab learning-lab--wide" data-testid="equivalence-lab">
  <div className="learning-lab__full"><div className="logic-mode-tabs"><Button variant={mode==='compare'?'primary':'secondary'} onClick={()=>setMode('compare')}>Compare truth vectors</Button><Button variant={mode==='transform'?'primary':'secondary'} onClick={()=>setMode('transform')}><WandSparkles size={15}/> Transform by rule</Button></div></div>
  {mode==='compare'?<>
   <div className="learning-lab__prompt"><p className="section-label">Semantic equivalence</p><h2>Compare every valuation, not the appearance.</h2><div className="two-column-fields"><label className="form-field"><span className="form-field__label">Expression A</span><input className="text-input logic-input" value={left} onChange={e=>{setLeft(e.target.value);setRevealed(false)}}/>{analysis.normalizedLeft&&<span className="form-field__hint">Normalized: {analysis.normalizedLeft}</span>}</label><label className="form-field"><span className="form-field__label">Expression B</span><input className="text-input logic-input" value={right} onChange={e=>{setRight(e.target.value);setRevealed(false)}}/>{analysis.normalizedRight&&<span className="form-field__hint">Normalized: {analysis.normalizedRight}</span>}</label></div><div className="preset-row">{PRESETS.map(p=><button key={p.label} className="text-chip" onClick={()=>{setLeft(p.left);setRight(p.right);setPrediction(undefined);setRevealed(false)}}>{p.label}</button>)}</div>{analysis.error&&<Feedback tone="error">{analysis.error}</Feedback>}{!analysis.error&&<><fieldset className="prediction-fieldset"><legend>Predict before revealing</legend><label><input type="radio" checked={prediction==='equivalent'} onChange={()=>{setPrediction('equivalent');setRevealed(false)}}/> Equivalent</label><label><input type="radio" checked={prediction==='different'} onChange={()=>{setPrediction('different');setRevealed(false)}}/> Not equivalent</label></fieldset><Button variant="primary" disabled={!prediction} onClick={reveal}>Check prediction</Button></>}</div>
   <div className="learning-lab__explain"><p className="section-label">Evidence</p>{!revealed?<p>The verdict stays hidden until you predict. One differing assignment is enough to disprove equivalence.</p>:analysis.result&&<><Feedback tone={predictionCorrect?'success':'error'}>{predictionCorrect?<CheckCircle2 size={18}/>:<XCircle size={18}/>}<strong>{analysis.result.equivalent?'Equivalent.':'Not equivalent.'}</strong> {analysis.result.equivalent?'Their truth vectors agree everywhere.':'A counterexample row makes the final truth values differ.'}</Feedback>{analysis.result.counterexample&&<div className="counterexample-box"><strong>First counterexample</strong><span>{analysis.result.symbols.map(symbol=>`${symbol}=${analysis.result!.counterexample![symbol]?'T':'F'}`).join(', ')}</span></div>}</>}</div>
   {revealed&&analysis.rows&&<div className="learning-lab__full"><div className="truth-table-scroll" tabIndex={0}><table className="truth-table"><thead><tr>{analysis.result?.symbols.map(symbol=><th key={symbol}>{symbol}</th>)}<th>A</th><th>B</th><th>Compare</th></tr></thead><tbody>{analysis.rows.map(row=><tr key={row.index} data-counterexample={row.left!==row.right}>{analysis.result?.symbols.map(symbol=><td key={symbol}>{row.assignment[symbol]?'T':'F'}</td>)}<td>{row.left?'T':'F'}</td><td>{row.right?'T':'F'}</td><td>{row.left===row.right?'same':<strong>differs</strong>}</td></tr>)}</tbody></table></div></div>}
  </>:<>
   <div className="learning-lab__full transform-workspace"><div className="math-panel"><div className="math-panel__head"><div><p className="section-label">Equivalence transformer</p><h2>Change exactly one rule at a time.</h2></div><Badge>{transformReached?'Goal reached':'In progress'}</Badge></div><div className="two-column-fields"><label className="form-field"><span className="form-field__label">Start</span><input className="text-input logic-input" value={start} onChange={e=>resetTransform(e.target.value,goal)}/></label><label className="form-field"><span className="form-field__label">Goal</span><input className="text-input logic-input" value={goal} onChange={e=>{setGoal(e.target.value);setTransformFeedback(undefined)}}/></label></div><div className="preset-row">{TRANSFORM_PRESETS.map(p=><button className="text-chip" key={p.label} onClick={()=>resetTransform(p.start,p.goal)}>{p.label}</button>)}</div><ol className="transform-history">{history.map((step,index)=><li key={`${index}-${step.expression}`}><span><code>{step.expression}</code>{step.ruleId&&<small>{step.ruleId} · {PROOF_RULES.find(r=>r.id===step.ruleId)?.name}</small>}</span></li>)}</ol>{transformReached&&<Feedback tone="success"><CheckCircle2 size={18}/><strong>Goal reached.</strong> Every accepted step used the named rule you selected.</Feedback>}</div>
   <aside className="math-panel"><p className="section-label">Next rewrite</p><label className="form-field"><span className="form-field__label">Rule</span><select className="select-input" value={rule} onChange={e=>setRule(e.target.value as EquivalenceRuleId)}>{EQUIV_RULES.map(item=><option key={item.id} value={item.id}>{item.id} · {item.name}</option>)}</select></label><label className="form-field"><span className="form-field__label">Resulting full expression</span><input className="text-input logic-input" value={nextExpression} onChange={e=>{setNextExpression(e.target.value);setTransformFeedback(undefined)}} placeholder="Rewrite one subexpression"/></label><Button variant="primary" disabled={!nextExpression.trim()||transformReached} onClick={()=>void addTransform()}>Apply {rule} <ArrowRight size={15}/></Button>{transformFeedback&&<Feedback tone={transformFeedback.ok?'success':'error'}>{transformFeedback.message}</Feedback>}<Button variant="ghost" onClick={()=>resetTransform()}><RotateCcw size={15}/> Reset transformation</Button><details className="reference-details"><summary>Rule map</summary><div className="transform-rule-grid">{EQUIV_RULES.map(item=><div key={item.id}><strong>{item.id}</strong><small>{item.name}</small></div>)}</div></details></aside></div>
  </>}
 </section>
}
