import { Rational, type RationalLike } from '@amat19/math-core';
export type PayoffMatrix=Rational[][];
export type SaddlePoint={row:number;col:number;value:Rational};
export function payoffMatrix(values:RationalLike[][]):PayoffMatrix {if(values.length<2||values[0]!.length<2)throw new RangeError('A payoff matrix needs at least two strategies per player for this lab.');const cols=values[0]!.length;if(values.some(r=>r.length!==cols))throw new RangeError('Every payoff row must have the same number of columns.');return values.map(r=>r.map(Rational.from));}
export function rowMinima(A:PayoffMatrix):Rational[]{return A.map(row=>row.reduce((m,v)=>v.compare(m)<0?v:m,row[0]!));}
export function columnMaxima(A:PayoffMatrix):Rational[]{return A[0]!.map((_,c)=>A.map(r=>r[c]!).reduce((m,v)=>v.compare(m)>0?v:m,A[0]![c]!));}
export function maximin(A:PayoffMatrix):Rational{return rowMinima(A).reduce((m,v)=>v.compare(m)>0?v:m);}
export function minimax(A:PayoffMatrix):Rational{return columnMaxima(A).reduce((m,v)=>v.compare(m)<0?v:m);}
export function saddlePoints(A:PayoffMatrix):SaddlePoint[]{const lo=maximin(A),hi=minimax(A);if(!lo.equals(hi))return[];const out:SaddlePoint[]=[];for(let r=0;r<A.length;r++)for(let c=0;c<A[0]!.length;c++)if(A[r]![c]!.equals(lo)&&A[r]![c]!.equals(rowMinima(A)[r]!)&&A[r]![c]!.equals(columnMaxima(A)[c]!))out.push({row:r,col:c,value:A[r]![c]!});return out;}
export function strictlyDominatedRows(A:PayoffMatrix):Array<{dominated:number;by:number}>{const out=[] as Array<{dominated:number;by:number}>;for(let i=0;i<A.length;i++)for(let j=0;j<A.length;j++){if(i===j)continue;if(A[j]!.every((v,c)=>v.compare(A[i]![c]!)>0))out.push({dominated:i,by:j});}return out;}
export function strictlyDominatedColumns(A:PayoffMatrix):Array<{dominated:number;by:number}>{const out=[] as Array<{dominated:number;by:number}>;const cols=A[0]!.length;for(let i=0;i<cols;i++)for(let j=0;j<cols;j++){if(i===j)continue;if(A.every(row=>row[j]!.compare(row[i]!)<0))out.push({dominated:i,by:j});}return out;}
export function solveZeroSum2x2(A:PayoffMatrix){if(A.length!==2||A[0]!.length!==2)throw new RangeError('The mixed-strategy formula here is for 2×2 zero-sum games.');const saddle=saddlePoints(A);if(saddle.length)return{kind:'pure' as const,saddles:saddle};const [[a,b],[c,d]]=A;const denominator=a!.subtract(b!).subtract(c!).add(d!);if(denominator.isZero())return{kind:'degenerate' as const,reason:'The standard 2×2 denominator is zero; dominance or a boundary strategy must be analyzed directly.'};const p=d!.subtract(c!).divide(denominator),q=d!.subtract(b!).divide(denominator),value=a!.multiply(d!).subtract(b!.multiply(c!)).divide(denominator);if(p.compare(0)<0||p.compare(1)>0||q.compare(0)<0||q.compare(1)>0)return{kind:'boundary' as const,p,q,value,reason:'The algebraic mixture falls outside [0,1], indicating a boundary/dominance solution rather than an interior mixed equilibrium.'};return{kind:'mixed' as const,pRow1:p,pRow2:Rational.one().subtract(p),qCol1:q,qCol2:Rational.one().subtract(q),value};}
