/// <reference lib="webworker" />
import { createSeededRandom, Rational } from '@amat19/math-core';
type Start={type:'start';seed:string;probability:string;trials:number;batchSize?:number};type Control={type:'pause'|'resume'|'cancel'};type Message=Start|Control;
type State={seed:string;p:Rational;trials:number;batchSize:number;trial:number;successes:number;random:()=>number;paused:boolean;cancelled:boolean;checkpoints:Array<{trials:number;successes:number;frequency:number}>};
let state:State|undefined;
function post(payload:unknown){self.postMessage(payload)}
function processBatch(){if(!state||state.cancelled)return;if(state.paused)return;const end=Math.min(state.trials,state.trial+state.batchSize);const threshold=state.p.toNumber();for(let i=state.trial+1;i<=end;i++){if(state.random()<threshold)state.successes+=1;state.trial=i;}state.checkpoints.push({trials:state.trial,successes:state.successes,frequency:state.successes/state.trial});post({type:'progress',trials:state.trial,total:state.trials,successes:state.successes,frequency:state.successes/state.trial});if(state.trial>=state.trials){post({type:'complete',result:{seed:state.seed,probability:state.p.toString(),trials:state.trials,successes:state.successes,frequency:new Rational(state.successes,state.trials).toString(),checkpoints:state.checkpoints}});state=undefined;return;}setTimeout(processBatch,0)}
self.onmessage=(event:MessageEvent<Message>)=>{try{const msg=event.data;if(msg.type==='start'){const p=Rational.from(msg.probability);if(!p.isProbability())throw new RangeError('Probability must lie between 0 and 1.');if(!Number.isInteger(msg.trials)||msg.trials<1||msg.trials>1_000_000)throw new RangeError('Trials must be 1–1,000,000.');state={seed:msg.seed,p,trials:msg.trials,batchSize:Math.max(100,Math.min(25000,Math.floor(msg.batchSize??Math.max(500,msg.trials/100)))),trial:0,successes:0,random:createSeededRandom(msg.seed),paused:false,cancelled:false,checkpoints:[]};post({type:'started'});processBatch();return;}if(!state)return;if(msg.type==='pause'){state.paused=true;post({type:'paused',trials:state.trial});}if(msg.type==='resume'){state.paused=false;post({type:'resumed'});setTimeout(processBatch,0);}if(msg.type==='cancel'){state.cancelled=true;post({type:'cancelled',trials:state.trial});state=undefined;}}catch(error){post({type:'error',error:error instanceof Error?error.message:'Simulation failed.'})}};
export {};
