import { Rational, type RationalLike } from '@amat19/math-core';
import { matrix, rref, type Matrix } from './matrix.ts';
export type Relation='<='|'>='|'=';
export type Constraint2D={a:number;b:number;relation:Relation;c:number;label?:string};
export type Objective2D={x:number;y:number;sense:'max'|'min'};
export type Point2D={x:number;y:number};
export type LpVertex={point:Point2D;value:number;activeConstraints:number[]};
export type GraphicalLpResult={status:'optimal'|'infeasible'|'unbounded';vertices:LpVertex[];optima:LpVertex[];message:string};
const EPS=1e-9;
function finiteConstraint(q:Constraint2D){for(const [name,v] of [['a',q.a],['b',q.b],['c',q.c]] as const)if(!Number.isFinite(v))throw new RangeError(`Constraint ${name} must be finite.`);if(Math.abs(q.a)<EPS&&Math.abs(q.b)<EPS)throw new RangeError('A constraint needs a nonzero x or y coefficient.');}
export function satisfiesConstraint(p:Point2D,q:Constraint2D):boolean {const lhs=q.a*p.x+q.b*p.y;if(q.relation==='<=')return lhs<=q.c+EPS;if(q.relation==='>=')return lhs>=q.c-EPS;return Math.abs(lhs-q.c)<=EPS;}
export function isFeasiblePoint(p:Point2D,constraints:Constraint2D[],nonnegative=true):boolean {if(nonnegative&&(p.x<-EPS||p.y<-EPS))return false;return constraints.every(q=>satisfiesConstraint(p,q));}
function lineIntersection(q1:Constraint2D,q2:Constraint2D):Point2D|null{const det=q1.a*q2.b-q2.a*q1.b;if(Math.abs(det)<EPS)return null;return{x:(q1.c*q2.b-q2.c*q1.b)/det,y:(q1.a*q2.c-q2.a*q1.c)/det};}
export function feasibleVertices(constraints:Constraint2D[],nonnegative=true):LpVertex[]{constraints.forEach(finiteConstraint);const boundaries=[...constraints];if(nonnegative){boundaries.push({a:1,b:0,relation:'=',c:0,label:'x=0'},{a:0,b:1,relation:'=',c:0,label:'y=0'});}const candidates:Point2D[]=[];for(let i=0;i<boundaries.length;i++)for(let j=i+1;j<boundaries.length;j++){const p=lineIntersection(boundaries[i]!,boundaries[j]!);if(p&&isFeasiblePoint(p,constraints,nonnegative))candidates.push(p);}const unique:Point2D[]=[];for(const p of candidates)if(!unique.some(q=>Math.hypot(p.x-q.x,p.y-q.y)<1e-7))unique.push({x:Math.abs(p.x)<EPS?0:p.x,y:Math.abs(p.y)<EPS?0:p.y});return unique.map(point=>({point,value:0,activeConstraints:constraints.map((q,i)=>Math.abs(q.a*point.x+q.b*point.y-q.c)<=1e-7?i:-1).filter(i=>i>=0)}));}
function directionSatisfies(d:Point2D,q:Constraint2D):boolean{const v=q.a*d.x+q.b*d.y;if(q.relation==='<=')return v<=EPS;if(q.relation==='>=')return v>=-EPS;return Math.abs(v)<=EPS;}
function recessionDirections(constraints:Constraint2D[],nonnegative=true):Point2D[]{const candidates:Point2D[]=[{x:1,y:0},{x:0,y:1}];for(const q of constraints)candidates.push({x:q.b,y:-q.a},{x:-q.b,y:q.a});return candidates.filter(d=>Math.hypot(d.x,d.y)>EPS&&(!nonnegative||(d.x>=-EPS&&d.y>=-EPS))&&constraints.every(q=>directionSatisfies(d,q)));}
export function solveGraphicalLP(constraints:Constraint2D[],objective:Objective2D,nonnegative=true):GraphicalLpResult {if(constraints.length===0)throw new RangeError('Add at least one structural constraint.');constraints.forEach(finiteConstraint);if(!Number.isFinite(objective.x)||!Number.isFinite(objective.y))throw new RangeError('Objective coefficients must be finite.');const vertices=feasibleVertices(constraints,nonnegative);if(vertices.length===0){const origin={x:0,y:0};if(!isFeasiblePoint(origin,constraints,nonnegative))return{status:'infeasible',vertices:[],optima:[],message:'No feasible corner was found and the origin is not feasible.'};}
 const improving=recessionDirections(constraints,nonnegative).some(d=>{const gain=objective.x*d.x+objective.y*d.y;return objective.sense==='max'?gain>EPS:gain<-EPS;});
 const scored=vertices.map(v=>({...v,value:objective.x*v.point.x+objective.y*v.point.y}));if(improving)return{status:'unbounded',vertices:scored,optima:[],message:'The feasible region contains a direction that improves the objective without bound.'};if(scored.length===0)return{status:'infeasible',vertices:[],optima:[],message:'No feasible corner point was found.'};const best=objective.sense==='max'?Math.max(...scored.map(v=>v.value)):Math.min(...scored.map(v=>v.value));const optima=scored.filter(v=>Math.abs(v.value-best)<=1e-7);return{status:'optimal',vertices:scored,optima,message:optima.length>1?'Multiple corner points attain the same optimum; the connecting feasible edge is also optimal.':'The objective reaches its optimum at the highlighted feasible corner.'};}

export type SimplexProblem={objective:RationalLike[];constraints:Array<{coefficients:RationalLike[];bound:RationalLike}>};
export type SimplexStep={iteration:number;tableau:Matrix;enteringColumn?:number;leavingRow?:number;pivot?:Rational;label:string};
export type SimplexResult={status:'optimal'|'unbounded'|'iteration-limit';objectiveValue?:Rational;solution?:Rational[];steps:SimplexStep[]};
export function simplexMax(problem:SimplexProblem,maxIterations=30):SimplexResult {const n=problem.objective.length,m=problem.constraints.length;if(n===0||m===0)throw new RangeError('Simplex needs variables and constraints.');if(problem.constraints.some(c=>c.coefficients.length!==n))throw new RangeError('Every simplex constraint needs one coefficient per decision variable.');const c=problem.objective.map(Rational.from);const rows:RationalLike[][]=problem.constraints.map((q,r)=>[...q.coefficients,...Array.from({length:m},(_,k)=>r===k?1:0),q.bound]);rows.push([...c.map(v=>v.negate()),...Array.from({length:m},()=>0),0]);let tab=matrix(rows);if(tab.slice(0,m).some(row=>row.at(-1)!.isNegative()))throw new RangeError('This educational simplex routine expects nonnegative right-hand sides.');const steps:SimplexStep[]=[{iteration:0,tableau:tab,label:'Initial tableau with slack variables'}];for(let iteration=1;iteration<=maxIterations;iteration++){const objectiveRow=tab[m]!;let entering=-1;for(let j=0;j<n+m;j++)if(objectiveRow[j]!.isNegative()&&(entering<0||objectiveRow[j]!.compare(objectiveRow[entering]!)<0))entering=j;if(entering<0){const solution=Array.from({length:n},()=>Rational.zero());for(let j=0;j<n;j++){let oneRow=-1,valid=true;for(let r=0;r<m;r++){const v=tab[r]![j]!;if(v.equals(1)){if(oneRow>=0){valid=false;break;}oneRow=r;}else if(!v.isZero()){valid=false;break;}}if(valid&&oneRow>=0)solution[j]=tab[oneRow]!.at(-1)!;}return{status:'optimal',objectiveValue:tab[m]!.at(-1)!,solution,steps};}
 let leaving=-1;let bestRatio:Rational|undefined;for(let r=0;r<m;r++){const coeff=tab[r]![entering]!;if(!coeff.isPositive())continue;const ratio=tab[r]!.at(-1)!.divide(coeff);if(ratio.isNegative())continue;if(!bestRatio||ratio.compare(bestRatio)<0){bestRatio=ratio;leaving=r;}}if(leaving<0)return{status:'unbounded',steps:[...steps,{iteration,tableau:tab,enteringColumn:entering,label:'Entering column has no positive pivot candidate'}]};const pivot=tab[leaving]![entering]!;let next=tab.map(row=>row.slice());next[leaving]=next[leaving]!.map(v=>v.divide(pivot));for(let r=0;r<next.length;r++){if(r===leaving)continue;const factor=next[r]![entering]!.negate();next[r]=next[r]!.map((v,j)=>v.add(factor.multiply(next[leaving]![j]!)));}tab=next;steps.push({iteration,tableau:tab,enteringColumn:entering,leavingRow:leaving,pivot,label:`Pivot on row ${leaving+1}, column ${entering+1}`});}return{status:'iteration-limit',steps};}
