import { useMemo, useState } from 'react';
import { analyzeDiscreteDistribution, binomialDistribution, distributionCdf } from '@amat19/domain-probability';
import { Button } from '../../ui/Button';import { Feedback } from '../../ui/Feedback';
type Entry={id:number;x:string;p:string};type Mode='custom'|'bernoulli'|'binomial';
export default function DistributionLab(){
 const[mode,setMode]=useState<Mode>('custom');const[entries,setEntries]=useState<Entry[]>([{id:1,x:'0',p:'1/4'},{id:2,x:'1',p:'1/2'},{id:3,x:'2',p:'1/4'}]);const[n,setN]=useState(4),[p,setP]=useState('1/2');
 const out=useMemo(()=>{try{const value=mode==='custom'?analyzeDiscreteDistribution(entries.map(e=>({value:e.x,probability:e.p}))):binomialDistribution(mode==='bernoulli'?1:n,p);return{value,cdf:distributionCdf(value),error:undefined}}catch(error){return{value:undefined,cdf:undefined,error:error instanceof Error?error.message:'Invalid distribution.'}}},[entries,mode,n,p]);
 const update=(id:number,patch:Partial<Entry>)=>setEntries(es=>es.map(e=>e.id===id?{...e,...patch}:e));
 return <section className="distribution-lab" data-testid="distribution-lab"><div className="distribution-lab__editor"><h2>Probability mass, expectation, spread, and cumulative probability share one model.</h2><p className="section-label">Supplemental discrete distribution</p><div className="distribution-presets"><Button variant={mode==='custom'?'primary':'secondary'} onClick={()=>setMode('custom')}>Custom</Button><Button variant={mode==='bernoulli'?'primary':'secondary'} onClick={()=>{setMode('bernoulli');setN(1)}}>Bernoulli</Button><Button variant={mode==='binomial'?'primary':'secondary'} onClick={()=>setMode('binomial')}>Binomial</Button></div>{mode==='custom'?<><table className="distribution-table"><thead><tr><th>x</th><th>P(X=x)</th><th></th></tr></thead><tbody>{entries.map(e=><tr key={e.id}><td><input aria-label={`Outcome ${e.id}`} value={e.x} onChange={ev=>update(e.id,{x:ev.target.value})}/></td><td><input aria-label={`Probability ${e.id}`} value={e.p} onChange={ev=>update(e.id,{p:ev.target.value})}/></td><td><Button variant="ghost" disabled={entries.length<=1} onClick={()=>setEntries(es=>es.filter(x=>x.id!==e.id))}>Remove</Button></td></tr>)}</tbody></table><Button variant="ghost" onClick={()=>setEntries(es=>[...es,{id:Math.max(...es.map(x=>x.id),0)+1,x:String(es.length),p:'0'}])}>+ Add outcome</Button></>:<div className="two-column-fields">{mode==='binomial'&&<label className="form-field"><span className="form-field__label">Trials n</span><input className="text-input" type="number" min="0" max="200" value={n} onChange={e=>setN(Number(e.target.value))}/></label>}<label className="form-field"><span className="form-field__label">Success probability p</span><input className="text-input" value={p} onChange={e=>setP(e.target.value)} placeholder="1/2"/></label></div>}{out.error&&<Feedback tone="error">{out.error}</Feedback>}</div>
 <div className="distribution-lab__visual">{out.value&&<><div className="math-panel__head"><div><h3>{mode==='custom'?'Your discrete model':mode==='bernoulli'?'Bernoulli model':`Binomial(${n}, ${p})`}</h3><p className="section-label">Probability mass function</p></div><span className="distribution-count">{out.value.outcomes.length} outcomes</span></div><div className="distribution-bars" aria-label="Probability mass diagram">{out.value.outcomes.map((e,i)=><div className="distribution-bar-wrap" key={i}><div className="distribution-bar" style={{height:`${Math.max(4,e.probability.toNumber()*220)}px`}}><span>{e.probability.toString()}</span></div><strong>{e.value.toString()}</strong></div>)}</div><div className="security-grid"><div className="formula-callout"><span>E[X]</span><strong>{out.value.expectedValue.toString()}</strong></div><div className="formula-callout"><span>E[X²]</span><strong>{out.value.secondMoment.toString()}</strong></div><div className="formula-callout"><span>Var(X)</span><strong>{out.value.variance.toString()}</strong></div><div className="formula-callout"><span>SD(X), decimal</span><strong>{Math.sqrt(Math.max(0,out.value.variance.toNumber())).toFixed(5)}</strong><small>display approximation of √Var(X)</small></div></div></>}</div>
 <aside className="distribution-lab__explain"><p className="section-label">CDF / exact arithmetic</p><p>Discrete probability requires probabilities to lie in [0,1] and sum exactly to 1.</p>{out.cdf&&<ol className="step-trace">{out.cdf.map((entry,index)=><li className="step-trace__item" key={index}><strong>P(X ≤ {entry.value.toString()})</strong><code>{entry.cumulative.toString()}</code></li>)}</ol>}<p><code>E[X] = Σ x·P(X=x)</code></p><p><code>Var(X) = E[X²] − E[X]²</code></p><p className="experimental-note">Distribution depth remains supplemental; the lab keeps exact fractions internally and only approximates the square root for display.</p></aside></section>
}
