import type { ModuleId } from './index.ts';

export type SkillScope='current'|'supplemental';
export type SkillNode={
  id:string;
  parentId?:string;
  module:ModuleId;
  title:string;
  description:string;
  prerequisiteIds:string[];
  lessonHref?:string;
  labHref:string;
  scope:SkillScope;
  keywords:string[];
};

export const skillGraph:SkillNode[]=[
 {id:'logic.proposition.identify',parentId:'logic.propositions',module:'logic',title:'Identify propositions',description:'Separate truth-valued statements from non-propositions.',prerequisiteIds:[],lessonHref:'/lessons/logic/propositions-and-connectives',labHref:'/workbenches/logic?mode=table',scope:'current',keywords:['statement','proposition','truth value']},
 {id:'logic.connective.identify',parentId:'logic.propositions',module:'logic',title:'Identify connectives',description:'Recognize negation, conjunction, disjunction, implication, and biconditional structure.',prerequisiteIds:['logic.proposition.identify'],lessonHref:'/lessons/logic/propositions-and-connectives',labHref:'/workbenches/logic?mode=table',scope:'current',keywords:['connective','and','or','if then','iff']},
 {id:'logic.symbolize',parentId:'logic.propositions',module:'logic',title:'Symbolize controlled statements',description:'Translate controlled language templates into canonical propositions.',prerequisiteIds:['logic.connective.identify'],lessonHref:'/lessons/logic/propositions-and-connectives',labHref:'/workbenches/logic?mode=translate',scope:'current',keywords:['symbolize','translate','logic symbols']},
 {id:'logic.truth-table.rows',parentId:'logic.truth-values',module:'logic',title:'Build truth-table rows',description:'Use 2ⁿ assignments and systematic T/F row patterns.',prerequisiteIds:['logic.connective.identify'],lessonHref:'/lessons/logic/truth-tables',labHref:'/workbenches/logic?mode=table',scope:'current',keywords:['rows','2^n','assignments']},
 {id:'logic.truth-table.evaluate',parentId:'logic.truth-values',module:'logic',title:'Evaluate truth-table columns',description:'Evaluate subexpressions from their child truth values.',prerequisiteIds:['logic.truth-table.rows'],lessonHref:'/lessons/logic/truth-tables',labHref:'/workbenches/logic?mode=table',scope:'current',keywords:['truth table','evaluate','column']},
 {id:'logic.truth-table.classify',parentId:'logic.truth-values',module:'logic',title:'Classify propositions',description:'Distinguish tautology, contradiction, and contingency.',prerequisiteIds:['logic.truth-table.evaluate'],lessonHref:'/lessons/logic/truth-tables',labHref:'/workbenches/logic?mode=table',scope:'current',keywords:['tautology','contradiction','contingency']},
 {id:'logic.equivalence.test',parentId:'logic.equivalence',module:'logic',title:'Test logical equivalence',description:'Compare final truth vectors and find the first counterexample.',prerequisiteIds:['logic.truth-table.evaluate'],lessonHref:'/lessons/logic/equivalence',labHref:'/workbenches/logic?mode=compare',scope:'current',keywords:['equivalence','counterexample']},
 {id:'logic.equivalence.transform',parentId:'logic.equivalence',module:'logic',title:'Transform with equivalence rules',description:'Apply one named equivalence law to a selected subexpression.',prerequisiteIds:['logic.equivalence.test'],lessonHref:'/lessons/logic/equivalence',labHref:'/workbenches/logic?mode=compare',scope:'current',keywords:['de morgan','double negation','material implication','rewrite']},
 {id:'logic.argument.validity',parentId:'logic.argument-validity',module:'logic',title:'Test argument validity',description:'Search for a row with true premises and a false conclusion.',prerequisiteIds:['logic.truth-table.evaluate'],lessonHref:'/lessons/logic/argument-validity',labHref:'/workbenches/logic?mode=argument',scope:'current',keywords:['argument','valid','counterexample']},
 {id:'logic.proof.direct',parentId:'logic.formal-proof',module:'logic',title:'Build direct proofs',description:'Derive a conclusion from premises using legal named rules.',prerequisiteIds:['logic.equivalence.transform','logic.argument.validity'],lessonHref:'/lessons/logic/formal-proof',labHref:'/workbenches/logic?mode=proof',scope:'current',keywords:['formal proof','direct proof','inference']},
 {id:'logic.proof.conditional',parentId:'logic.formal-proof',module:'logic',title:'Conditional proof scopes',description:'Open and discharge an assumption to establish an implication.',prerequisiteIds:['logic.proof.direct'],lessonHref:'/lessons/logic/formal-proof',labHref:'/workbenches/logic?mode=proof',scope:'supplemental',keywords:['conditional proof','assumption','subproof']},
 {id:'logic.proof.indirect',parentId:'logic.formal-proof',module:'logic',title:'Indirect proof scopes',description:'Assume a negated goal, derive contradiction, and discharge the scope.',prerequisiteIds:['logic.proof.direct'],lessonHref:'/lessons/logic/formal-proof',labHref:'/workbenches/logic?mode=proof',scope:'supplemental',keywords:['indirect proof','contradiction']},

 {id:'probability.counting.product-rule',parentId:'probability.counting',module:'probability',title:'Product rule',description:'Multiply independent stage counts in sequential choices.',prerequisiteIds:[],lessonHref:'/lessons/probability/counting-models',labHref:'/workbenches/probability?mode=counting',scope:'current',keywords:['product rule','stages','counting']},
 {id:'probability.counting.permutation',parentId:'probability.counting',module:'probability',title:'Permutation model',description:'Count ordered selections without repetition.',prerequisiteIds:['probability.counting.product-rule'],lessonHref:'/lessons/probability/counting-models',labHref:'/workbenches/probability?mode=counting',scope:'current',keywords:['permutation','order','nPr']},
 {id:'probability.counting.combination',parentId:'probability.counting',module:'probability',title:'Combination model',description:'Count unordered selections without repetition.',prerequisiteIds:['probability.counting.product-rule'],lessonHref:'/lessons/probability/counting-models',labHref:'/workbenches/probability?mode=counting',scope:'current',keywords:['combination','choose','nCr']},
 {id:'probability.inclusion-exclusion.two-set',parentId:'probability.inclusion-exclusion',module:'probability',title:'Two-set inclusion–exclusion',description:'Count a union while subtracting double-counted overlap.',prerequisiteIds:['probability.counting.product-rule'],lessonHref:'/lessons/probability/inclusion-exclusion',labHref:'/workbenches/probability?mode=counting',scope:'current',keywords:['union','intersection','inclusion exclusion']},
 {id:'probability.basic.exact',parentId:'probability.basic',module:'probability',title:'Exact finite probability',description:'Represent favorable over total outcomes as an exact rational value.',prerequisiteIds:['probability.counting.combination'],lessonHref:'/lessons/probability/basic-probability',labHref:'/workbenches/probability?mode=conditioning',scope:'current',keywords:['probability','fraction','sample space']},
 {id:'probability.conditional.denominator',parentId:'probability.conditional',module:'probability',title:'Conditional sample space',description:'Restrict the denominator to the conditioning event.',prerequisiteIds:['probability.basic.exact'],lessonHref:'/lessons/probability/conditional-probability',labHref:'/workbenches/probability?mode=conditioning',scope:'current',keywords:['conditional','denominator','given']},
 {id:'probability.independence.test',parentId:'probability.independence',module:'probability',title:'Test independence',description:'Compare exact conditional and marginal probabilities or product identities.',prerequisiteIds:['probability.conditional.denominator'],lessonHref:'/lessons/probability/independence',labHref:'/workbenches/probability?mode=conditioning',scope:'current',keywords:['independence','dependent']},
 {id:'probability.bayes.posterior',module:'probability',title:'Bayes posterior',description:'Update a prior probability after observing evidence using a synchronized tree/table model.',prerequisiteIds:['probability.conditional.denominator'],lessonHref:'/lessons/probability/bayes',labHref:'/workbenches/probability?mode=bayes',scope:'supplemental',keywords:['bayes','posterior','prior','likelihood']},
 {id:'probability.distribution.expectation',parentId:'probability.distribution',module:'probability',title:'Expected value',description:'Compute ΣxP(X=x) exactly for a discrete distribution.',prerequisiteIds:['probability.basic.exact'],lessonHref:'/lessons/probability/discrete-distributions',labHref:'/lessons/probability/discrete-distributions',scope:'supplemental',keywords:['expected value','mean','distribution']},
 {id:'probability.distribution.variance',parentId:'probability.distribution',module:'probability',title:'Variance',description:'Use E[X²] − E[X]² to measure spread.',prerequisiteIds:['probability.distribution.expectation'],lessonHref:'/lessons/probability/discrete-distributions',labHref:'/lessons/probability/discrete-distributions',scope:'supplemental',keywords:['variance','spread','standard deviation']},
 {id:'probability.simulation.frequency',parentId:'probability.simulation',module:'probability',title:'Empirical frequency',description:'Compare deterministic seeded simulation results with theoretical probability.',prerequisiteIds:['probability.basic.exact'],lessonHref:'/lessons/probability/simulation',labHref:'/workbenches/probability?mode=verify',scope:'supplemental',keywords:['simulation','frequency','seed']},

 {id:'finance.simple-interest',parentId:'finance.interest',module:'finance',title:'Simple interest',description:'Accumulate principal when interest is earned only on the original principal.',prerequisiteIds:[],lessonHref:'/lessons/finance/interest-measurement',labHref:'/workbenches/finance?scenario=cashflows',scope:'current',keywords:['simple interest','principal']},
 {id:'finance.compound-interest',parentId:'finance.interest',module:'finance',title:'Compound interest',description:'Accumulate principal with interest on the accumulated balance.',prerequisiteIds:['finance.simple-interest'],lessonHref:'/lessons/finance/interest-measurement',labHref:'/workbenches/finance?scenario=cashflows',scope:'current',keywords:['compound interest','accumulation']},
 {id:'finance.nominal-effective',parentId:'finance.rate-equivalence',module:'finance',title:'Nominal/effective equivalence',description:'Match one-year accumulation across nominal and effective rate conventions.',prerequisiteIds:['finance.compound-interest'],lessonHref:'/lessons/finance/equivalent-rates',labHref:'/workbenches/finance?scenario=cashflows',scope:'current',keywords:['nominal','effective rate','conversion']},
 {id:'finance.tvm.focal-date',parentId:'finance.tvm',module:'finance',title:'Focal-date valuation',description:'Move every cash flow to one common date before combining values.',prerequisiteIds:['finance.compound-interest'],lessonHref:'/lessons/finance/time-value',labHref:'/workbenches/finance?scenario=cashflows',scope:'current',keywords:['time value','focal date','discount']},
 {id:'finance.annuity.immediate',parentId:'finance.annuity',module:'finance',title:'Annuity-immediate',description:'Value level end-of-period payments.',prerequisiteIds:['finance.tvm.focal-date'],lessonHref:'/lessons/finance/annuities',labHref:'/workbenches/finance?scenario=annuity',scope:'current',keywords:['annuity immediate','payment']},
 {id:'finance.annuity.due',parentId:'finance.annuity',module:'finance',title:'Annuity-due',description:'Shift an annuity-immediate one period for beginning-of-period payments.',prerequisiteIds:['finance.annuity.immediate'],lessonHref:'/lessons/finance/annuities',labHref:'/workbenches/finance?scenario=annuity',scope:'current',keywords:['annuity due','beginning']},
 {id:'finance.bond-price',parentId:'finance.bonds',module:'finance',title:'Bond price decomposition',description:'Combine coupon-annuity value with discounted redemption.',prerequisiteIds:['finance.annuity.immediate','finance.nominal-effective'],lessonHref:'/lessons/finance/bonds',labHref:'/workbenches/finance?scenario=bond',scope:'supplemental',keywords:['bond','coupon','redemption','premium','discount']},

 {id:'linear.matrix.add',parentId:'linear.operations',module:'linear',title:'Matrix addition',description:'Combine same-dimension matrices entry by entry.',prerequisiteIds:[],lessonHref:'/lessons/linear/matrix-operations',labHref:'/workbenches/linear?goal=rref',scope:'current',keywords:['matrix addition']},
 {id:'linear.matrix.multiply',parentId:'linear.operations',module:'linear',title:'Matrix multiplication',description:'Build each product entry from one row-column dot product.',prerequisiteIds:['linear.matrix.add'],lessonHref:'/lessons/linear/matrix-operations',labHref:'/workbenches/linear?goal=rref',scope:'current',keywords:['matrix multiplication','dot product']},
 {id:'linear.matrix.rref',parentId:'linear.rref',module:'linear',title:'Row reduction',description:'Apply elementary row operations to reach RREF.',prerequisiteIds:['linear.matrix.multiply'],lessonHref:'/lessons/linear/row-reduction',labHref:'/workbenches/linear?goal=rref',scope:'current',keywords:['rref','gauss jordan','row operation']},
 {id:'linear.system.solve',parentId:'linear.systems',module:'linear',title:'Classify and solve systems',description:'Read unique, infinite, or inconsistent solutions from RREF.',prerequisiteIds:['linear.matrix.rref'],lessonHref:'/lessons/linear/inverse-and-systems',labHref:'/workbenches/linear?goal=system',scope:'current',keywords:['system','unique','infinite','inconsistent']},
 {id:'linear.inverse.gauss-jordan',parentId:'linear.inverse',module:'linear',title:'Matrix inverse by Gauss–Jordan',description:'Reduce [A|I] to [I|A⁻¹] when an inverse exists.',prerequisiteIds:['linear.matrix.rref'],lessonHref:'/lessons/linear/inverse-and-systems',labHref:'/workbenches/linear?goal=inverse',scope:'current',keywords:['inverse','gauss jordan']},

 {id:'applications.lp.model',parentId:'applications.lp',module:'applications',title:'Model a graphical LP',description:'Translate an objective and inequalities into a two-variable feasible-region model.',prerequisiteIds:['linear.system.solve'],lessonHref:'/lessons/applications/graphical-lp',labHref:'/workbenches/applications?mode=linear',scope:'current',keywords:['linear programming','constraint','objective']},
 {id:'applications.lp.corner-point',parentId:'applications.lp',module:'applications',title:'Corner-point optimization',description:'Evaluate the objective at feasible vertices and interpret multiple optima.',prerequisiteIds:['applications.lp.model'],lessonHref:'/lessons/applications/graphical-lp',labHref:'/workbenches/applications?mode=linear',scope:'current',keywords:['feasible region','corner','optimum']},
 {id:'applications.simplex.pivot',parentId:'applications.simplex',module:'applications',title:'Simplex pivot step',description:'Choose entering/leaving variables and perform a legal tableau pivot.',prerequisiteIds:['applications.lp.corner-point'],lessonHref:'/lessons/applications/simplex',labHref:'/workbenches/applications?mode=advanced',scope:'supplemental',keywords:['simplex','pivot','ratio test']},
 {id:'applications.game.security',parentId:'applications.game-theory',module:'applications',title:'Maximin and minimax',description:'Compare player security levels in a zero-sum payoff matrix.',prerequisiteIds:['linear.matrix.add'],lessonHref:'/lessons/applications/game-theory',labHref:'/workbenches/applications?mode=game',scope:'current',keywords:['maximin','minimax','zero sum']},
 {id:'applications.game.mixed-2x2',parentId:'applications.game-theory',module:'applications',title:'2×2 mixed strategy',description:'Solve an interior 2×2 zero-sum mixture when no pure saddle exists.',prerequisiteIds:['applications.game.security'],lessonHref:'/lessons/applications/game-theory',labHref:'/workbenches/applications?mode=game',scope:'current',keywords:['mixed strategy','saddle']},
 {id:'applications.markov.step',parentId:'applications.markov',module:'applications',title:'Markov transitions',description:'Propagate a state distribution through a transition matrix.',prerequisiteIds:['linear.matrix.multiply','probability.basic.exact'],lessonHref:'/lessons/applications/markov',labHref:'/workbenches/applications?mode=advanced',scope:'supplemental',keywords:['markov','transition','state']}
];

export function getSkillNode(id:string):SkillNode|undefined{return skillGraph.find(skill=>skill.id===id)}
export function getModuleSkillGraph(module:ModuleId):SkillNode[]{return skillGraph.filter(skill=>skill.module===module)}
export function getPrerequisites(id:string):SkillNode[]{const node=getSkillNode(id);return node?node.prerequisiteIds.map(getSkillNode).filter((x):x is SkillNode=>Boolean(x)):[]}
export function searchSkills(query:string):SkillNode[]{const q=query.trim().toLowerCase();if(!q)return[];return skillGraph.filter(skill=>[skill.title,skill.description,...skill.keywords].some(text=>text.toLowerCase().includes(q))).slice(0,12)}
