import { useEffect, useRef, useState } from 'react';
import { Rational } from '@amat19/math-core';
import { Button } from '../../ui/Button';import { Feedback } from '../../ui/Feedback';
type Point={trials:number;successes:number;frequency:number};type WorkerResult={seed:string;probability:string;trials:number;successes:number;frequency:string;checkpoints:Point[]};
export default function ProbabilitySimulationLab(){const[numerator,setNumerator]=useState(1),[denominator,setDenominator]=useState(3),[trials,setTrials]=useState(5000),[seed,setSeed]=useState('amat19-simulation'),[result,setResult]=useState<WorkerResult>(),[error,setError]=useState<string>(),[running,setRunning]=useState(false);const workerRef=useRef<Worker | null>(null);
 useEffect(()=>()=>workerRef.current?.terminate(),[]);
 function run(){let p:Rational;try{p=new Rational(numerator,denominator);if(!p.isProbability())throw new RangeError('Probability must be between 0 and 1.');}catch(e){setError(e instanceof Error?e.message:'Invalid probability.');return;}workerRef.current?.terminate();const worker=new Worker(new URL('../../../workers/probability-simulation.worker.ts',import.meta.url),{type:'module'});workerRef.current=worker;setRunning(true);setError(undefined);worker.onmessage=(event:MessageEvent<{ok:boolean;result?:WorkerResult;error?:string}>)=>{setRunning(false);if(event.data.ok&&event.data.result)setResult(event.data.result);else setError(event.data.error??'Simulation failed.');worker.terminate();};worker.onerror=()=>{setRunning(false);setError('The simulation worker could not run in this browser.');worker.terminate();};worker.postMessage({seed,probability:p.toString(),trials});}
 const theory=denominator?numerator/denominator:0;return <section className="simulation-lab" data-testid="probability-simulation-lab"><div className="simulation-lab__controls"><p className="section-label">Supplemental probability experiment</p><h2>Watch empirical frequency approach—not prove—the theoretical probability.</h2><div className="two-column-fields"><label className="form-field"><span className="form-field__label">Probability numerator</span><input className="text-input" type="number" step="1" value={numerator} onChange={e=>setNumerator(Number(e.target.value))}/></label><label className="form-field"><span className="form-field__label">Probability denominator</span><input className="text-input" type="number" min="1" step="1" value={denominator} onChange={e=>setDenominator(Number(e.target.value))}/></label><label className="form-field"><span className="form-field__label">Trials</span><input className="text-input" type="number" min="1" max="1000000" step="100" value={trials} onChange={e=>setTrials(Number(e.target.value))}/></label><label className="form-field"><span className="form-field__label">Reproducible seed</span><input className="text-input" value={seed} onChange={e=>setSeed(e.target.value)}/></label></div><Button variant="primary" type="button" disabled={running} onClick={run}>{running?'Running in worker…':'Run seeded simulation'}</Button>{error&&<Feedback tone="error" role="alert">{error}</Feedback>}<p className="experimental-note">The same seed, probability, and trial count reproduce the same experiment. A close empirical frequency supports intuition; it is not a mathematical proof of the theoretical probability.</p></div><div className="simulation-lab__visual">{result?<><SimulationChart points={result.checkpoints} theory={theory}/><div className="formula-callout"><span>Observed frequency</span><strong>{result.successes}/{result.trials} = {result.frequency}</strong><small>decimal ≈ {(result.successes/result.trials).toFixed(5)} · theoretical = {result.probability}</small></div></>:<div className="empty-state"><strong>No experiment yet.</strong><p>Set a model and run it. Computation stays off the UI thread.</p></div>}</div></section>}
function SimulationChart({points,theory}:{points:Point[];theory:number}){const maxX=points.at(-1)?.trials??1;const sx=(x:number)=>55+500*x/maxX,sy=(y:number)=>250-200*y;const path=points.map((p,i)=>`${i?'L':'M'} ${sx(p.trials)} ${sy(p.frequency)}`).join(' ');return <figure className="simulation-chart"><svg viewBox="0 0 620 300" role="img" aria-label="Empirical frequency convergence plot"><line className="axis" x1="55" y1="250" x2="570" y2="250"/><line className="axis" x1="55" y1="250" x2="55" y2="35"/><line className="theory-line" x1="55" y1={sy(theory)} x2="570" y2={sy(theory)}/><path className="frequency-path" d={path}/><text x="575" y="255">trials</text><text x="65" y={Math.max(20,sy(theory)-8)}>theory {theory.toFixed(3)}</text></svg><figcaption>The horizontal line is theoretical probability; the path is cumulative empirical frequency at deterministic checkpoints.</figcaption></figure>}
